from __future__ import annotations

from uuid import UUID, uuid4

from ..auth import AsyncAuthSchemes, AuthSchemes
from ..core import (
    AllSchemes,
    ApiResult,
    AsyncAllSchemes,
    AsyncRawClient,
    RawClient,
    RawError,
    RequestOptionsOrDict,
    SecuredRawResponse,
    async_json_decoder,
    json_body,
    json_decoder,
    param,
    raw_error_response,
)
from ..models.link_token_create_request import LinkTokenCreateRequest, LinkTokenCreateRequestDict
from ..models.link_token_create_response import LinkTokenCreateResponse
from ..models.link_token_get_request import LinkTokenGetRequest, LinkTokenGetRequestDict
from ..models.link_token_get_response import LinkTokenGetResponse
from ..server.server import Server


class Link:
    def __init__(self, client: RawClient, server: Server, auth: AuthSchemes) -> None:
        self._with_raw_response = LinkWithRawResponse(client, server, auth)

    def link_token_create(
        self,
        body: LinkTokenCreateRequest | LinkTokenCreateRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> LinkTokenCreateResponse:
        """The ``/link/token/create`` endpoint creates a ``link_token``, which is required as a parameter when
        initializing Link. Once Link has been initialized, it returns a ``public_token``, which can then be exchanged
        for an ``access_token`` via ``/item/public_token/exchange`` as part of the main Link flow.

        A ``link_token`` generated by ``/link/token/create`` is also used to initialize other Link flows, such as the
        update mode flow for tokens with expired credentials, or the Payment Initiation (Europe) flow.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.link_token_create(body, request_options=request_options).unwrap()

    def link_token_get(
        self,
        body: LinkTokenGetRequest | LinkTokenGetRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> LinkTokenGetResponse:
        """The ``/link/token/get`` endpoint gets information about a previously-created ``link_token`` using the
        ``/link/token/create`` endpoint. It can be useful for debugging purposes.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return self._with_raw_response.link_token_get(body, request_options=request_options).unwrap()

    @property
    def with_raw_response(self) -> LinkWithRawResponse:
        return self._with_raw_response


class AsyncLink:
    def __init__(self, client: AsyncRawClient, server: Server, auth: AsyncAuthSchemes) -> None:
        self._with_raw_response = AsyncLinkWithRawResponse(client, server, auth)

    async def link_token_create(
        self,
        body: LinkTokenCreateRequest | LinkTokenCreateRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> LinkTokenCreateResponse:
        """The ``/link/token/create`` endpoint creates a ``link_token``, which is required as a parameter when
        initializing Link. Once Link has been initialized, it returns a ``public_token``, which can then be exchanged
        for an ``access_token`` via ``/item/public_token/exchange`` as part of the main Link flow.

        A ``link_token`` generated by ``/link/token/create`` is also used to initialize other Link flows, such as the
        update mode flow for tokens with expired credentials, or the Payment Initiation (Europe) flow.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (await self._with_raw_response.link_token_create(body, request_options=request_options)).unwrap()

    async def link_token_get(
        self,
        body: LinkTokenGetRequest | LinkTokenGetRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> LinkTokenGetResponse:
        """The ``/link/token/get`` endpoint gets information about a previously-created ``link_token`` using the
        ``/link/token/create`` endpoint. It can be useful for debugging purposes.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            OK

        Raises:
            ApiError: If the API responds with an error status code. ``error`` is ``RawError``."""
        return (await self._with_raw_response.link_token_get(body, request_options=request_options)).unwrap()

    @property
    def with_raw_response(self) -> AsyncLinkWithRawResponse:
        return self._with_raw_response


class LinkWithRawResponse(SecuredRawResponse[RawClient, Server, AuthSchemes]):
    def link_token_create(
        self,
        body: LinkTokenCreateRequest | LinkTokenCreateRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[LinkTokenCreateResponse, RawError]:
        """The ``/link/token/create`` endpoint creates a ``link_token``, which is required as a parameter when
        initializing Link. Once Link has been initialized, it returns a ``public_token``, which can then be exchanged
        for an ``access_token`` via ``/item/public_token/exchange`` as part of the main Link flow.

        A ``link_token`` generated by ``/link/token/create`` is also used to initialize other Link flows, such as the
        update mode flow for tokens with expired credentials, or the Payment Initiation (Europe) flow.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default("/link/token/create"),
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=json_body[LinkTokenCreateRequest | LinkTokenCreateRequestDict](body),
            auth_scheme=AllSchemes(self._auth.plaid_client_id, self._auth.plaid_secret, self._auth.plaid_version),
            decoder=json_decoder[LinkTokenCreateResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    def link_token_get(
        self,
        body: LinkTokenGetRequest | LinkTokenGetRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[LinkTokenGetResponse, RawError]:
        """The ``/link/token/get`` endpoint gets information about a previously-created ``link_token`` using the
        ``/link/token/create`` endpoint. It can be useful for debugging purposes.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return self._client.execute(
            http_method="POST",
            url_template=self._server.default("/link/token/get"),
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=json_body[LinkTokenGetRequest | LinkTokenGetRequestDict](body),
            auth_scheme=AllSchemes(self._auth.plaid_client_id, self._auth.plaid_secret, self._auth.plaid_version),
            decoder=json_decoder[LinkTokenGetResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )


class AsyncLinkWithRawResponse(SecuredRawResponse[AsyncRawClient, Server, AsyncAuthSchemes]):
    async def link_token_create(
        self,
        body: LinkTokenCreateRequest | LinkTokenCreateRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[LinkTokenCreateResponse, RawError]:
        """The ``/link/token/create`` endpoint creates a ``link_token``, which is required as a parameter when
        initializing Link. Once Link has been initialized, it returns a ``public_token``, which can then be exchanged
        for an ``access_token`` via ``/item/public_token/exchange`` as part of the main Link flow.

        A ``link_token`` generated by ``/link/token/create`` is also used to initialize other Link flows, such as the
        update mode flow for tokens with expired credentials, or the Payment Initiation (Europe) flow.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default("/link/token/create"),
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=json_body[LinkTokenCreateRequest | LinkTokenCreateRequestDict](body),
            auth_scheme=AsyncAllSchemes(self._auth.plaid_client_id, self._auth.plaid_secret, self._auth.plaid_version),
            decoder=async_json_decoder[LinkTokenCreateResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )

    async def link_token_get(
        self,
        body: LinkTokenGetRequest | LinkTokenGetRequestDict,
        *,
        request_options: RequestOptionsOrDict | None = None,
    ) -> ApiResult[LinkTokenGetResponse, RawError]:
        """The ``/link/token/get`` endpoint gets information about a previously-created ``link_token`` using the
        ``/link/token/create`` endpoint. It can be useful for debugging purposes.

        Args:
            body: The request body.
            request_options: Per-call overrides for this one request, such as a timeout, extra headers, or its retry
                count and statuses.

        Returns:
            An ``ApiResult`` holding the deserialized response or the error body."""
        return await self._client.execute(
            http_method="POST",
            url_template=self._server.default("/link/token/get"),
            headers=[param[UUID]("Idempotency-Key", uuid4())],
            body=json_body[LinkTokenGetRequest | LinkTokenGetRequestDict](body),
            auth_scheme=AsyncAllSchemes(self._auth.plaid_client_id, self._auth.plaid_secret, self._auth.plaid_version),
            decoder=async_json_decoder[LinkTokenGetResponse],
            error_mapper=raw_error_response,
            request_options=request_options,
        )
