"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.exceptions.api_exception import ApiException


class ErrorErrorException(ApiException):
    def __init__(self, reason, response):
        """Initialize ErrorErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ErrorErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.error_type =\
            dictionary.get("error_type")\
            if dictionary.get("error_type")\
                else None
        self.error_code =\
            dictionary.get("error_code")\
            if dictionary.get("error_code")\
                else None
        self.error_message =\
            dictionary.get("error_message")\
            if dictionary.get("error_message")\
                else None
        self.display_message =\
            dictionary.get("display_message")\
            if dictionary.get("display_message")\
                else None
        self.request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None
        self.causes =\
            dictionary.get("causes")\
            if dictionary.get("causes")\
                else None
        self.status =\
            dictionary.get("status")\
            if "status" in dictionary.keys()\
                else None
        self.documentation_url =\
            dictionary.get("documentation_url")\
            if dictionary.get("documentation_url")\
                else None
        self.suggested_action =\
            dictionary.get("suggested_action")\
            if dictionary.get("suggested_action")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _error_type=self.error_type
        _error_code=self.error_code
        _error_message=self.error_message
        _display_message=self.display_message
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _causes=(
            self.causes
            if hasattr(self, "causes")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _documentation_url=(
            self.documentation_url
            if hasattr(self, "documentation_url")
            else None
        )
        _suggested_action=(
            self.suggested_action
            if hasattr(self, "suggested_action")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"error_type={_error_type!s}, "
            f"error_code={_error_code!s}, "
            f"error_message={_error_message!s}, "
            f"display_message={_display_message!s}, "
            f"request_id={_request_id!s}, "
            f"causes={_causes!s}, "
            f"status={_status!s}, "
            f"documentation_url={_documentation_url!s}, "
            f"suggested_action={_suggested_action!s}, "
            f")"
        )
