"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AccountsGetRequestOptions(object):
    """Implementation of the 'AccountsGetRequestOptions' model.

    An optional object to filter `/accounts/get` results.

    Attributes:
        account_ids (List[str]): An array of `account_ids` to retrieve for the
            Account.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_ids": "account_ids",
    }

    _optionals = [
        "account_ids",
    ]

    def __init__(
        self,
        account_ids=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccountsGetRequestOptions instance."""
        # Initialize members of the class
        if account_ids is not APIHelper.SKIP:
            self.account_ids = account_ids

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_ids =\
            dictionary.get("account_ids")\
            if dictionary.get("account_ids")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_ids,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_ids=(
            self.account_ids
            if hasattr(self, "account_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_ids={_account_ids!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_ids=(
            self.account_ids
            if hasattr(self, "account_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_ids={_account_ids!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
