"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AccountType(object):
    """Implementation of the 'AccountType' enum.

    `investment:` Investment account
    `credit:` Credit card
    `depository:` Depository account
    `loan:` Loan account
    `brokerage`: An investment account. Used for `/assets/` endpoints only; other
    endpoints use `investment`.
    `other:` Non-specified account type
    See the [Account type
    schema](https://plaid.com/docs/api/accounts#account-type-schema) for a full
    listing of account types and corresponding subtypes.

    Attributes:
        INVESTMENT: The enum member of type str.
        CREDIT: The enum member of type str.
        DEPOSITORY: The enum member of type str.
        LOAN: The enum member of type str.
        BROKERAGE: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    INVESTMENT = "investment"

    CREDIT = "credit"

    DEPOSITORY = "depository"

    LOAN = "loan"

    BROKERAGE = "brokerage"

    OTHER = "other"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
