"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AccountSelectionCardinality(object):
    """Implementation of the 'AccountSelectionCardinality' enum.

    The application requires that accounts be limited to a specific cardinality.
    `MULTI_SELECT`: indicates that the user should be allowed to pick multiple
    accounts.
    `SINGLE_SELECT`: indicates that the user should be allowed to pick only a single
    account.
    `ALL`: indicates that the user must share all of their accounts and should not be
    given the opportunity to de-select

    Attributes:
        SINGLE_SELECT: The enum member of type str.
        MULTI_SELECT: The enum member of type str.
        ALL: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    SINGLE_SELECT = "SINGLE_SELECT"

    MULTI_SELECT = "MULTI_SELECT"

    ALL = "ALL"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
