"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AccountFilter(object):
    """Implementation of the 'AccountFilter' model.

    Enumerates the account subtypes that the application wishes for the user to be
    able to select from. For more details refer to Plaid documentation on account
    filters.

    Attributes:
        depository (List[str]): A list of account subtypes to be filtered.
        credit (List[str]): A list of account subtypes to be filtered.
        loan (List[str]): A list of account subtypes to be filtered.
        investment (List[str]): A list of account subtypes to be filtered.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "depository": "depository",
        "credit": "credit",
        "loan": "loan",
        "investment": "investment",
    }

    _optionals = [
        "depository",
        "credit",
        "loan",
        "investment",
    ]

    def __init__(
        self,
        depository=APIHelper.SKIP,
        credit=APIHelper.SKIP,
        loan=APIHelper.SKIP,
        investment=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccountFilter instance."""
        # Initialize members of the class
        if depository is not APIHelper.SKIP:
            self.depository = depository
        if credit is not APIHelper.SKIP:
            self.credit = credit
        if loan is not APIHelper.SKIP:
            self.loan = loan
        if investment is not APIHelper.SKIP:
            self.investment = investment

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        depository =\
            dictionary.get("depository")\
            if dictionary.get("depository")\
                else APIHelper.SKIP
        credit =\
            dictionary.get("credit")\
            if dictionary.get("credit")\
                else APIHelper.SKIP
        loan =\
            dictionary.get("loan")\
            if dictionary.get("loan")\
                else APIHelper.SKIP
        investment =\
            dictionary.get("investment")\
            if dictionary.get("investment")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(depository,
                   credit,
                   loan,
                   investment,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _depository=(
            self.depository
            if hasattr(self, "depository")
            else None
        )
        _credit=(
            self.credit
            if hasattr(self, "credit")
            else None
        )
        _loan=(
            self.loan
            if hasattr(self, "loan")
            else None
        )
        _investment=(
            self.investment
            if hasattr(self, "investment")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"depository={_depository!r}, "
            f"credit={_credit!r}, "
            f"loan={_loan!r}, "
            f"investment={_investment!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _depository=(
            self.depository
            if hasattr(self, "depository")
            else None
        )
        _credit=(
            self.credit
            if hasattr(self, "credit")
            else None
        )
        _loan=(
            self.loan
            if hasattr(self, "loan")
            else None
        )
        _investment=(
            self.investment
            if hasattr(self, "investment")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"depository={_depository!s}, "
            f"credit={_credit!s}, "
            f"loan={_loan!s}, "
            f"investment={_investment!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
