"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AccountsBalanceGetRequestOptions(object):
    """Implementation of the 'AccountsBalanceGetRequestOptions' model.

    An optional object to filter `/accounts/balance/get` results.

    Attributes:
        account_ids (List[str]): A list of `account_ids` to retrieve for the Item.
            The default value is `null`.  Note: An error will be returned if a
            provided `account_id` is not associated with the Item.
        min_last_updated_datetime (datetime): Timestamp in [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) format
            (`YYYY-MM-DDTHH:mm:ssZ`) indicating the oldest acceptable balance when
            making a request to `/accounts/balance/get`.  If the balance that is
            pulled for `ins_128026` (Capital One) is older than the given timestamp,
            an `INVALID_REQUEST` error with the code of
            `LAST_UPDATED_DATETIME_OUT_OF_RANGE` will be returned with the most
            recent timestamp for the requested account contained in the response.
            This field is only used when the institution is `ins_128026` (Capital
            One), in which case a value must be provided or an `INVALID_REQUEST`
            error with the code of `INVALID_FIELD` will be returned. For all other
            institutions, this field is ignored.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_ids": "account_ids",
        "min_last_updated_datetime": "min_last_updated_datetime",
    }

    _optionals = [
        "account_ids",
        "min_last_updated_datetime",
    ]

    def __init__(
        self,
        account_ids=APIHelper.SKIP,
        min_last_updated_datetime=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccountsBalanceGetRequestOptions instance."""
        # Initialize members of the class
        if account_ids is not APIHelper.SKIP:
            self.account_ids = account_ids
        if min_last_updated_datetime is not APIHelper.SKIP:
            self.min_last_updated_datetime =\
                 APIHelper.apply_datetime_converter(
                min_last_updated_datetime, APIHelper.RFC3339DateTime)\
                 if min_last_updated_datetime else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_ids =\
            dictionary.get("account_ids")\
            if dictionary.get("account_ids")\
                else APIHelper.SKIP
        min_last_updated_datetime = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("min_last_updated_datetime")).datetime\
            if dictionary.get("min_last_updated_datetime") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_ids,
                   min_last_updated_datetime,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_ids=(
            self.account_ids
            if hasattr(self, "account_ids")
            else None
        )
        _min_last_updated_datetime=(
            self.min_last_updated_datetime
            if hasattr(self, "min_last_updated_datetime")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_ids={_account_ids!r}, "
            f"min_last_updated_datetime={_min_last_updated_datetime!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_ids=(
            self.account_ids
            if hasattr(self, "account_ids")
            else None
        )
        _min_last_updated_datetime=(
            self.min_last_updated_datetime
            if hasattr(self, "min_last_updated_datetime")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_ids={_account_ids!s}, "
            f"min_last_updated_datetime={_min_last_updated_datetime!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
