"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class Address2(object):
    """Implementation of the 'Address2' model.

    Attributes:
        city (str): The full city name.
        street (str): The listed street address.
        line_1 (str): Street address line 1.
        line_2 (str): Street address line 2.
        postal_code (str): 5 digit postal code.
        region (str): The region or state Example: `"NC"`
        state_code (str): The region or state Example: `"NC"`
        country (str): The country of the address.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "city": "city",
        "street": "street",
        "line_1": "line1",
        "line_2": "line2",
        "postal_code": "postal_code",
        "region": "region",
        "state_code": "state_code",
        "country": "country",
    }

    _optionals = [
        "city",
        "street",
        "line_1",
        "line_2",
        "postal_code",
        "region",
        "state_code",
        "country",
    ]

    _nullables = [
        "city",
        "street",
        "line_1",
        "line_2",
        "postal_code",
        "region",
        "state_code",
        "country",
    ]

    def __init__(
        self,
        city=APIHelper.SKIP,
        street=APIHelper.SKIP,
        line_1=APIHelper.SKIP,
        line_2=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        region=APIHelper.SKIP,
        state_code=APIHelper.SKIP,
        country=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Address2 instance."""
        # Initialize members of the class
        if city is not APIHelper.SKIP:
            self.city = city
        if street is not APIHelper.SKIP:
            self.street = street
        if line_1 is not APIHelper.SKIP:
            self.line_1 = line_1
        if line_2 is not APIHelper.SKIP:
            self.line_2 = line_2
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if region is not APIHelper.SKIP:
            self.region = region
        if state_code is not APIHelper.SKIP:
            self.state_code = state_code
        if country is not APIHelper.SKIP:
            self.country = country

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        city =\
            dictionary.get("city")\
            if "city" in dictionary.keys()\
                else APIHelper.SKIP
        street =\
            dictionary.get("street")\
            if "street" in dictionary.keys()\
                else APIHelper.SKIP
        line_1 =\
            dictionary.get("line1")\
            if "line1" in dictionary.keys()\
                else APIHelper.SKIP
        line_2 =\
            dictionary.get("line2")\
            if "line2" in dictionary.keys()\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postal_code")\
            if "postal_code" in dictionary.keys()\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if "region" in dictionary.keys()\
                else APIHelper.SKIP
        state_code =\
            dictionary.get("state_code")\
            if "state_code" in dictionary.keys()\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if "country" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(city,
                   street,
                   line_1,
                   line_2,
                   postal_code,
                   region,
                   state_code,
                   country,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _street=(
            self.street
            if hasattr(self, "street")
            else None
        )
        _line_1=(
            self.line_1
            if hasattr(self, "line_1")
            else None
        )
        _line_2=(
            self.line_2
            if hasattr(self, "line_2")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _state_code=(
            self.state_code
            if hasattr(self, "state_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!r}, "
            f"street={_street!r}, "
            f"line_1={_line_1!r}, "
            f"line_2={_line_2!r}, "
            f"postal_code={_postal_code!r}, "
            f"region={_region!r}, "
            f"state_code={_state_code!r}, "
            f"country={_country!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _street=(
            self.street
            if hasattr(self, "street")
            else None
        )
        _line_1=(
            self.line_1
            if hasattr(self, "line_1")
            else None
        )
        _line_2=(
            self.line_2
            if hasattr(self, "line_2")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _state_code=(
            self.state_code
            if hasattr(self, "state_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!s}, "
            f"street={_street!s}, "
            f"line_1={_line_1!s}, "
            f"line_2={_line_2!s}, "
            f"postal_code={_postal_code!s}, "
            f"region={_region!s}, "
            f"state_code={_state_code!s}, "
            f"country={_country!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
