"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class ApplicationGetRequest(object):
    """Implementation of the 'ApplicationGetRequest' model.

    ApplicationGetResponse defines the schema for `/application/get`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        application_id (str): This field will map to the application ID that is
            returned from /item/applications/list, or provided to the institution in
            an oauth redirect.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_id": "client_id",
        "secret": "secret",
        "application_id": "application_id",
    }

    def __init__(
        self,
        client_id=None,
        secret=None,
        application_id=None,
        additional_properties=None):
        """Initialize a ApplicationGetRequest instance."""
        # Initialize members of the class
        self.client_id = client_id
        self.secret = secret
        self.application_id = application_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else None
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else None
        application_id =\
            dictionary.get("application_id")\
            if dictionary.get("application_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(client_id,
                   secret,
                   application_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=self.client_id
        _secret=self.secret
        _application_id=self.application_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"application_id={_application_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=self.client_id
        _secret=self.secret
        _application_id=self.application_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"application_id={_application_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
