"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.asset_report import AssetReport
from plaid.models.warning import Warning


class AssetReportGetResponse(object):
    """Implementation of the 'AssetReportGetResponse' model.

    AssetReportGetResponse defines the response schema for `/asset_report/get`

    Attributes:
        report (AssetReport): An object representing an Asset Report
        warnings (List[Warning]): If the Asset Report generation was successful but
            identity information cannot be returned, this array will contain
            information about the errors causing identity information to be missing
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "report": "report",
        "warnings": "warnings",
        "request_id": "request_id",
    }

    def __init__(
        self,
        report=None,
        warnings=None,
        request_id=None,
        additional_properties=None):
        """Initialize a AssetReportGetResponse instance."""
        # Initialize members of the class
        self.report = report
        self.warnings = warnings
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        report =\
            AssetReport.from_dictionary(
                dictionary.get("report"))\
                if dictionary.get("report") else None
        warnings = None
        if dictionary.get("warnings") is not None:
            warnings = [
                Warning.from_dictionary(x)
                    for x in dictionary.get("warnings")
            ]
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(report,
                   warnings,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _report=self.report
        _warnings=self.warnings
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"report={_report!r}, "
            f"warnings={_warnings!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _report=self.report
        _warnings=self.warnings
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"report={_report!s}, "
            f"warnings={_warnings!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
