"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.asset_report_user import AssetReportUser


class AssetReportCreateRequestOptions(object):
    """Implementation of the 'AssetReportCreateRequestOptions' model.

    An optional object to filter `/asset_report/create` results. If provided, must be
    non-`null`. The optional `user` object is required for the report to be eligible
    for Fannie Mae's Day 1 Certainty program.

    Attributes:
        client_report_id (str): Client-generated identifier, which can be used by
            lenders to track loan applications.
        webhook (str): URL to which Plaid will send Assets webhooks, for example when
            the requested Asset Report is ready.
        user (AssetReportUser): The user object allows you to provide additional
            information about the user to be appended to the Asset Report. All fields
            are optional. The `first_name`, `last_name`, and `ssn` fields are
            required if you would like the Report to be eligible for Fannie Mae’s Day
            1 Certainty™ program.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_report_id": "client_report_id",
        "webhook": "webhook",
        "user": "user",
    }

    _optionals = [
        "client_report_id",
        "webhook",
        "user",
    ]

    def __init__(
        self,
        client_report_id=APIHelper.SKIP,
        webhook=APIHelper.SKIP,
        user=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssetReportCreateRequestOptions instance."""
        # Initialize members of the class
        if client_report_id is not APIHelper.SKIP:
            self.client_report_id = client_report_id
        if webhook is not APIHelper.SKIP:
            self.webhook = webhook
        if user is not APIHelper.SKIP:
            self.user = user

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        client_report_id =\
            dictionary.get("client_report_id")\
            if dictionary.get("client_report_id")\
                else APIHelper.SKIP
        webhook =\
            dictionary.get("webhook")\
            if dictionary.get("webhook")\
                else APIHelper.SKIP
        user =\
            AssetReportUser.from_dictionary(
                dictionary.get("user"))\
                if "user" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(client_report_id,
                   webhook,
                   user,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_report_id=(
            self.client_report_id
            if hasattr(self, "client_report_id")
            else None
        )
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_report_id={_client_report_id!r}, "
            f"webhook={_webhook!r}, "
            f"user={_user!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_report_id=(
            self.client_report_id
            if hasattr(self, "client_report_id")
            else None
        )
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_report_id={_client_report_id!s}, "
            f"webhook={_webhook!s}, "
            f"user={_user!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
