"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AssetReportFilterRequest(object):
    """Implementation of the 'AssetReportFilterRequest' model.

    AssetReportFilterRequest defines the request schema for `/asset_report/filter`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        asset_report_token (str): A token that can be provided to endpoints such as
            `/asset_report/get` or `/asset_report/pdf/get` to fetch or update an
            Asset Report.
        account_ids_to_exclude (List[str]): The accounts to exclude from the Asset
            Report, identified by `account_id`.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "asset_report_token": "asset_report_token",
        "account_ids_to_exclude": "account_ids_to_exclude",
        "client_id": "client_id",
        "secret": "secret",
    }

    _optionals = [
        "client_id",
        "secret",
    ]

    def __init__(
        self,
        asset_report_token=None,
        account_ids_to_exclude=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssetReportFilterRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.asset_report_token = asset_report_token
        self.account_ids_to_exclude = account_ids_to_exclude

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        asset_report_token =\
            dictionary.get("asset_report_token")\
            if dictionary.get("asset_report_token")\
                else None
        account_ids_to_exclude =\
            dictionary.get("account_ids_to_exclude")\
            if dictionary.get("account_ids_to_exclude")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(asset_report_token,
                   account_ids_to_exclude,
                   client_id,
                   secret,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _asset_report_token=self.asset_report_token
        _account_ids_to_exclude=self.account_ids_to_exclude
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"asset_report_token={_asset_report_token!r}, "
            f"account_ids_to_exclude={_account_ids_to_exclude!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _asset_report_token=self.asset_report_token
        _account_ids_to_exclude=self.account_ids_to_exclude
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"asset_report_token={_asset_report_token!s}, "
            f"account_ids_to_exclude={_account_ids_to_exclude!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
