"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.asset_report_create_request_options import (
    AssetReportCreateRequestOptions,
)


class AssetReportCreateRequest(object):
    """Implementation of the 'AssetReportCreateRequest' model.

    AssetReportCreateRequest defines the request schema for `/asset_report/create`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        access_tokens (List[str]): An array of access tokens corresponding to the
            Items that will be included in the report. The `assets` product must have
            been initialized for the Items during link; the Assets product cannot be
            added after initialization.
        days_requested (int): The maximum integer number of days of history to
            include in the Asset Report. If using Fannie Mae Day 1 Certainty,
            `days_requested` must be at least 61 for new originations or at least 31
            for refinancings.
        options (AssetReportCreateRequestOptions): An optional object to filter
            `/asset_report/create` results. If provided, must be non-`null`. The
            optional `user` object is required for the report to be eligible for
            Fannie Mae's Day 1 Certainty program.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access_tokens": "access_tokens",
        "days_requested": "days_requested",
        "client_id": "client_id",
        "secret": "secret",
        "options": "options",
    }

    _optionals = [
        "client_id",
        "secret",
        "options",
    ]

    def __init__(
        self,
        access_tokens=None,
        days_requested=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        options=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssetReportCreateRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.access_tokens = access_tokens
        self.days_requested = days_requested
        if options is not APIHelper.SKIP:
            self.options = options

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        access_tokens =\
            dictionary.get("access_tokens")\
            if dictionary.get("access_tokens")\
                else None
        days_requested =\
            dictionary.get("days_requested")\
            if dictionary.get("days_requested")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        options =\
            AssetReportCreateRequestOptions.from_dictionary(
                dictionary.get("options"))\
                if "options" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(access_tokens,
                   days_requested,
                   client_id,
                   secret,
                   options,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _access_tokens=self.access_tokens
        _days_requested=self.days_requested
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"access_tokens={_access_tokens!r}, "
            f"days_requested={_days_requested!r}, "
            f"options={_options!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _access_tokens=self.access_tokens
        _days_requested=self.days_requested
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"access_tokens={_access_tokens!s}, "
            f"days_requested={_days_requested!s}, "
            f"options={_options!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
