"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AssetReportAuditCopyRemoveRequest(object):
    """Implementation of the 'AssetReportAuditCopyRemoveRequest' model.

    AssetReportAuditCopyRemoveRequest defines the request schema for
    `/asset_report/audit_copy/remove`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        audit_copy_token (str): The `audit_copy_token` granting access to the Audit
            Copy you would like to revoke.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "audit_copy_token": "audit_copy_token",
        "client_id": "client_id",
        "secret": "secret",
    }

    _optionals = [
        "client_id",
        "secret",
    ]

    def __init__(
        self,
        audit_copy_token=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssetReportAuditCopyRemoveRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.audit_copy_token = audit_copy_token

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        audit_copy_token =\
            dictionary.get("audit_copy_token")\
            if dictionary.get("audit_copy_token")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(audit_copy_token,
                   client_id,
                   secret,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _audit_copy_token=self.audit_copy_token
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"audit_copy_token={_audit_copy_token!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _audit_copy_token=self.audit_copy_token
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"audit_copy_token={_audit_copy_token!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
