"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AssetReportGetRequest(object):
    """Implementation of the 'AssetReportGetRequest' model.

    AssetReportGetRequest defines the request schema for `/asset_report/get`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        asset_report_token (str): A token that can be provided to endpoints such as
            `/asset_report/get` or `/asset_report/pdf/get` to fetch or update an
            Asset Report.
        include_insights (bool): `true` if you would like to retrieve the Asset
            Report with Insights, `false` otherwise. This field defaults to `false`
            if omitted.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "asset_report_token": "asset_report_token",
        "client_id": "client_id",
        "secret": "secret",
        "include_insights": "include_insights",
    }

    _optionals = [
        "client_id",
        "secret",
        "include_insights",
    ]

    def __init__(
        self,
        asset_report_token=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        include_insights=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssetReportGetRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.asset_report_token = asset_report_token
        if include_insights is not APIHelper.SKIP:
            self.include_insights = include_insights

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        asset_report_token =\
            dictionary.get("asset_report_token")\
            if dictionary.get("asset_report_token")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        include_insights =\
            dictionary.get("include_insights")\
            if "include_insights" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(asset_report_token,
                   client_id,
                   secret,
                   include_insights,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _asset_report_token=self.asset_report_token
        _include_insights=(
            self.include_insights
            if hasattr(self, "include_insights")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"asset_report_token={_asset_report_token!r}, "
            f"include_insights={_include_insights!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _asset_report_token=self.asset_report_token
        _include_insights=(
            self.include_insights
            if hasattr(self, "include_insights")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"asset_report_token={_asset_report_token!s}, "
            f"include_insights={_include_insights!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
