"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class AutomaticallyVerifiedWebhook(object):
    """Implementation of the 'AutomaticallyVerifiedWebhook' model.

    Fired when an Item is verified via automated micro-deposits. We recommend
    communicating to your users when this event is received to notify them that their
    account is verified and ready for use.

    Attributes:
        webhook_type (str): `AUTH`
        webhook_code (str): `AUTOMATICALLY_VERIFIED`
        account_id (str): The `account_id` of the account associated with the webhook
        item_id (str): The `item_id` of the Item associated with this webhook,
            warning, or error
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "webhook_type": "webhook_type",
        "webhook_code": "webhook_code",
        "account_id": "account_id",
        "item_id": "item_id",
    }

    def __init__(
        self,
        webhook_type=None,
        webhook_code=None,
        account_id=None,
        item_id=None,
        additional_properties=None):
        """Initialize a AutomaticallyVerifiedWebhook instance."""
        # Initialize members of the class
        self.webhook_type = webhook_type
        self.webhook_code = webhook_code
        self.account_id = account_id
        self.item_id = item_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        webhook_type =\
            dictionary.get("webhook_type")\
            if dictionary.get("webhook_type")\
                else None
        webhook_code =\
            dictionary.get("webhook_code")\
            if dictionary.get("webhook_code")\
                else None
        account_id =\
            dictionary.get("account_id")\
            if dictionary.get("account_id")\
                else None
        item_id =\
            dictionary.get("item_id")\
            if dictionary.get("item_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(webhook_type,
                   webhook_code,
                   account_id,
                   item_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _webhook_type=self.webhook_type
        _webhook_code=self.webhook_code
        _account_id=self.account_id
        _item_id=self.item_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook_type={_webhook_type!r}, "
            f"webhook_code={_webhook_code!r}, "
            f"account_id={_account_id!r}, "
            f"item_id={_item_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _webhook_type=self.webhook_type
        _webhook_code=self.webhook_code
        _account_id=self.account_id
        _item_id=self.item_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook_type={_webhook_type!s}, "
            f"webhook_code={_webhook_code!s}, "
            f"account_id={_account_id!s}, "
            f"item_id={_item_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
