"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.bank_transfer_balance import (
    BankTransferBalance,
)


class BankTransferBalanceGetResponse(object):
    """Implementation of the 'BankTransferBalanceGetResponse' model.

    Defines the response schema for `/bank_transfer/balance/get`

    Attributes:
        balance (BankTransferBalance): The model property of type BankTransferBalance.
        origination_account_id (str): The ID of the origination account that this
            balance belongs to.
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "balance": "balance",
        "origination_account_id": "origination_account_id",
        "request_id": "request_id",
    }

    _nullables = [
        "origination_account_id",
    ]

    def __init__(
        self,
        balance=None,
        origination_account_id=None,
        request_id=None,
        additional_properties=None):
        """Initialize a BankTransferBalanceGetResponse instance."""
        # Initialize members of the class
        self.balance = balance
        self.origination_account_id = origination_account_id
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        balance =\
            BankTransferBalance.from_dictionary(
                dictionary.get("balance"))\
                if dictionary.get("balance") else None
        origination_account_id =\
            dictionary.get("origination_account_id")\
            if dictionary.get("origination_account_id")\
                else None
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(balance,
                   origination_account_id,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _balance=self.balance
        _origination_account_id=self.origination_account_id
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"balance={_balance!r}, "
            f"origination_account_id={_origination_account_id!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _balance=self.balance
        _origination_account_id=self.origination_account_id
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"balance={_balance!s}, "
            f"origination_account_id={_origination_account_id!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
