"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.bank_transfer_event import (
    BankTransferEvent,
)


class BankTransferEventSyncResponse(object):
    """Implementation of the 'BankTransferEventSyncResponse' model.

    Defines the response schema for `/bank_transfer/event/sync`

    Attributes:
        bank_transfer_events (List[BankTransferEvent]): The model property of type
            List[BankTransferEvent].
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bank_transfer_events": "bank_transfer_events",
        "request_id": "request_id",
    }

    def __init__(
        self,
        bank_transfer_events=None,
        request_id=None,
        additional_properties=None):
        """Initialize a BankTransferEventSyncResponse instance."""
        # Initialize members of the class
        self.bank_transfer_events = bank_transfer_events
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        bank_transfer_events = None
        if dictionary.get("bank_transfer_events") is not None:
            bank_transfer_events = [
                BankTransferEvent.from_dictionary(x)
                    for x in dictionary.get("bank_transfer_events")
            ]
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(bank_transfer_events,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _bank_transfer_events=self.bank_transfer_events
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bank_transfer_events={_bank_transfer_events!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _bank_transfer_events=self.bank_transfer_events
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bank_transfer_events={_bank_transfer_events!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
