"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class BankTransferSweepListRequest(object):
    """Implementation of the 'BankTransferSweepListRequest' model.

    BankTransferSweepListRequest defines the request schema for
    `/bank_transfer/sweep/list`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        origination_account_id (str): If multiple origination accounts are available,
            `origination_account_id` must be used to specify the account that the
            sweeps belong to.
        start_id (int): Starting ID of sweeps to return.
        start_time (datetime): The start datetime of sweeps to return (RFC 3339
            format).
        end_time (datetime): The end datetime of sweeps to return (RFC 3339 format).
        count (int): The maximum number of sweeps to return.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_id": "client_id",
        "secret": "secret",
        "origination_account_id": "origination_account_id",
        "start_id": "start_id",
        "start_time": "start_time",
        "end_time": "end_time",
        "count": "count",
    }

    _optionals = [
        "client_id",
        "secret",
        "origination_account_id",
        "start_id",
        "start_time",
        "end_time",
        "count",
    ]

    _nullables = [
        "origination_account_id",
        "start_id",
        "start_time",
        "end_time",
        "count",
    ]

    def __init__(
        self,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        origination_account_id=APIHelper.SKIP,
        start_id=APIHelper.SKIP,
        start_time=APIHelper.SKIP,
        end_time=APIHelper.SKIP,
        count=25,
        additional_properties=None):
        """Initialize a BankTransferSweepListRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        if origination_account_id is not APIHelper.SKIP:
            self.origination_account_id = origination_account_id
        if start_id is not APIHelper.SKIP:
            self.start_id = start_id
        if start_time is not APIHelper.SKIP:
            self.start_time =\
                 APIHelper.apply_datetime_converter(
                start_time, APIHelper.RFC3339DateTime)\
                 if start_time else None
        if end_time is not APIHelper.SKIP:
            self.end_time =\
                 APIHelper.apply_datetime_converter(
                end_time, APIHelper.RFC3339DateTime)\
                 if end_time else None
        self.count = count

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        origination_account_id =\
            dictionary.get("origination_account_id")\
            if "origination_account_id" in dictionary.keys()\
                else APIHelper.SKIP
        start_id =\
            dictionary.get("start_id")\
            if "start_id" in dictionary.keys()\
                else APIHelper.SKIP
        if "start_time" in dictionary.keys():
            start_time = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("start_time")).datetime\
                if dictionary.get("start_time") else None

        else:
            start_time = APIHelper.SKIP
        if "end_time" in dictionary.keys():
            end_time = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("end_time")).datetime\
                if dictionary.get("end_time") else None

        else:
            end_time = APIHelper.SKIP
        count =\
            dictionary.get("count")\
            if dictionary.get("count")\
                else 25

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(client_id,
                   secret,
                   origination_account_id,
                   start_id,
                   start_time,
                   end_time,
                   count,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _origination_account_id=(
            self.origination_account_id
            if hasattr(self, "origination_account_id")
            else None
        )
        _start_id=(
            self.start_id
            if hasattr(self, "start_id")
            else None
        )
        _start_time=(
            self.start_time
            if hasattr(self, "start_time")
            else None
        )
        _end_time=(
            self.end_time
            if hasattr(self, "end_time")
            else None
        )
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"origination_account_id={_origination_account_id!r}, "
            f"start_id={_start_id!r}, "
            f"start_time={_start_time!r}, "
            f"end_time={_end_time!r}, "
            f"count={_count!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _origination_account_id=(
            self.origination_account_id
            if hasattr(self, "origination_account_id")
            else None
        )
        _start_id=(
            self.start_id
            if hasattr(self, "start_id")
            else None
        )
        _start_time=(
            self.start_time
            if hasattr(self, "start_time")
            else None
        )
        _end_time=(
            self.end_time
            if hasattr(self, "end_time")
            else None
        )
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"origination_account_id={_origination_account_id!s}, "
            f"start_id={_start_id!s}, "
            f"start_time={_start_time!s}, "
            f"end_time={_end_time!s}, "
            f"count={_count!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
