"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Branch(object):
    """Implementation of the 'Branch' enum.

    If the user is currently serving in the US military, the branch of the military
    they are serving in

    Attributes:
        ENUM_AIR FORCE: The enum member of type str.
        ARMY: The enum member of type str.
        ENUM_COAST GUARD: The enum member of type str.
        MARINES: The enum member of type str.
        NAVY: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    ENUM_AIR_FORCE = "AIR FORCE"

    ARMY = "ARMY"

    ENUM_COAST_GUARD = "COAST GUARD"

    MARINES = "MARINES"

    NAVY = "NAVY"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
