"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class CanonicalDescription(object):
    """Implementation of the 'CanonicalDescription' enum.

    Commonly used term to describe the line item.

    Attributes:
        BONUS: The enum member of type str.
        COMMISSION: The enum member of type str.
        OVERTIME: The enum member of type str.
        ENUM_PAID TIME OFF: The enum member of type str.
        ENUM_REGULAR PAY: The enum member of type str.
        VACATION: The enum member of type str.
        ENUM_EMPLOYEE MEDICARE: The enum member of type str.
        FICA: The enum member of type str.
        ENUM_SOCIAL SECURITY EMPLOYEE TAX: The enum member of type str.
        MEDICAL: The enum member of type str.
        VISION: The enum member of type str.
        DENTAL: The enum member of type str.
        ENUM_NET PAY: The enum member of type str.
        TAXES: The enum member of type str.
        NOT_FOUND: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    BONUS = "BONUS"

    COMMISSION = "COMMISSION"

    OVERTIME = "OVERTIME"

    ENUM_PAID_TIME_OFF = "PAID TIME OFF"

    ENUM_REGULAR_PAY = "REGULAR PAY"

    VACATION = "VACATION"

    ENUM_EMPLOYEE_MEDICARE = "EMPLOYEE MEDICARE"

    FICA = "FICA"

    ENUM_SOCIAL_SECURITY_EMPLOYEE_TAX = "SOCIAL SECURITY EMPLOYEE TAX"

    MEDICAL = "MEDICAL"

    VISION = "VISION"

    DENTAL = "DENTAL"

    ENUM_NET_PAY = "NET PAY"

    TAXES = "TAXES"

    NOT_FOUND = "NOT_FOUND"

    OTHER = "OTHER"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
