"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class CustomerInitiatedReturnRisk(object):
    """Implementation of the 'CustomerInitiatedReturnRisk' model.

    The object contains a risk score and a risk tier that evaluate the transaction
    return risk of an unauthorized debit. Common return codes in this category
    include: “R05”, "R07", "R10", "R11", "R29". These returns typically have a return
    time frame of up to 60 calendar days. During this period, the customer of
    financial institutions can dispute a transaction as unauthorized.

    Attributes:
        score (int): A score from 0-99 that indicates the transaction return risk: a
            higher risk score suggests a higher return likelihood.
        risk_tier (int): A tier corresponding to the projected likelihood that the
            transaction, if initiated, will be subject to a return.  In the
            `customer_initiated_return_risk` object, there are five risk tiers
            corresponding to the scores:   1: Predicted customer-initiated return
            incidence rate between 0.00% - 0.02%   2: Predicted customer-initiated
            return incidence rate between 0.02% - 0.05%   3: Predicted
            customer-initiated return incidence rate between 0.05% - 0.1%   4:
            Predicted customer-initiated return incidence rate between 0.1% - 0.5%
            5: Predicted customer-initiated return incidence rate greater than 0.5%
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "score": "score",
        "risk_tier": "risk_tier",
    }

    def __init__(
        self,
        score=None,
        risk_tier=None,
        additional_properties=None):
        """Initialize a CustomerInitiatedReturnRisk instance."""
        # Initialize members of the class
        self.score = score
        self.risk_tier = risk_tier

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        score =\
            dictionary.get("score")\
            if dictionary.get("score")\
                else None
        risk_tier =\
            dictionary.get("risk_tier")\
            if dictionary.get("risk_tier")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(score,
                   risk_tier,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _score=self.score
        _risk_tier=self.risk_tier
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"score={_score!r}, "
            f"risk_tier={_risk_tier!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _score=self.score
        _risk_tier=self.risk_tier
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"score={_score!s}, "
            f"risk_tier={_risk_tier!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
