"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Decision(object):
    """Implementation of the 'Decision' enum.

    A decision regarding the proposed transfer.
    `approved` – The proposed transfer has received the end user's consent and has
    been approved for processing. Plaid has also reviewed the proposed transfer and
    has approved it for processing.
    `permitted` – Plaid was unable to fetch the information required to approve or
    decline the proposed transfer. You may proceed with the transfer, but further
    review is recommended. Plaid is awaiting further instructions from the client.
    `declined` – Plaid reviewed the proposed transfer and declined processing. Refer
    to the `code` field in the `decision_rationale` object for details.

    Attributes:
        APPROVED: The enum member of type str.
        PERMITTED: The enum member of type str.
        DECLINED: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    APPROVED = "approved"

    PERMITTED = "permitted"

    DECLINED = "declined"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
