"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class DepositoryAccount(object):
    """Implementation of the 'DepositoryAccount' model.

    An account type holding cash, in which funds are deposited. Supported products
    for `depository` accounts are: Auth, Balance, Transactions, Identity, Payment
    Initiation, and Assets.

    Attributes:
        checking (str): Checking account
        savings (str): Savings account
        hsa (str): Health Savings Account (US only) that can only hold cash
        cd (str): Certificate of deposit account
        money_market (str): Money market account
        paypal (str): PayPal depository account
        prepaid (str): Prepaid debit card
        cash_management (str): A cash management account, typically a cash account at
            a brokerage
        ebt (str): An Electronic Benefit Transfer (EBT) account, used by certain
            public assistance programs to distribute funds (US only)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "checking": "checking",
        "savings": "savings",
        "hsa": "hsa",
        "cd": "cd",
        "money_market": "money market",
        "paypal": "paypal",
        "prepaid": "prepaid",
        "cash_management": "cash management",
        "ebt": "ebt",
    }

    def __init__(
        self,
        checking=None,
        savings=None,
        hsa=None,
        cd=None,
        money_market=None,
        paypal=None,
        prepaid=None,
        cash_management=None,
        ebt=None,
        additional_properties=None):
        """Initialize a DepositoryAccount instance."""
        # Initialize members of the class
        self.checking = checking
        self.savings = savings
        self.hsa = hsa
        self.cd = cd
        self.money_market = money_market
        self.paypal = paypal
        self.prepaid = prepaid
        self.cash_management = cash_management
        self.ebt = ebt

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        checking =\
            dictionary.get("checking")\
            if dictionary.get("checking")\
                else None
        savings =\
            dictionary.get("savings")\
            if dictionary.get("savings")\
                else None
        hsa =\
            dictionary.get("hsa")\
            if dictionary.get("hsa")\
                else None
        cd =\
            dictionary.get("cd")\
            if dictionary.get("cd")\
                else None
        money_market =\
            dictionary.get("money market")\
            if dictionary.get("money market")\
                else None
        paypal =\
            dictionary.get("paypal")\
            if dictionary.get("paypal")\
                else None
        prepaid =\
            dictionary.get("prepaid")\
            if dictionary.get("prepaid")\
                else None
        cash_management =\
            dictionary.get("cash management")\
            if dictionary.get("cash management")\
                else None
        ebt =\
            dictionary.get("ebt")\
            if dictionary.get("ebt")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(checking,
                   savings,
                   hsa,
                   cd,
                   money_market,
                   paypal,
                   prepaid,
                   cash_management,
                   ebt,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _checking=self.checking
        _savings=self.savings
        _hsa=self.hsa
        _cd=self.cd
        _money_market=self.money_market
        _paypal=self.paypal
        _prepaid=self.prepaid
        _cash_management=self.cash_management
        _ebt=self.ebt
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"checking={_checking!r}, "
            f"savings={_savings!r}, "
            f"hsa={_hsa!r}, "
            f"cd={_cd!r}, "
            f"money_market={_money_market!r}, "
            f"paypal={_paypal!r}, "
            f"prepaid={_prepaid!r}, "
            f"cash_management={_cash_management!r}, "
            f"ebt={_ebt!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _checking=self.checking
        _savings=self.savings
        _hsa=self.hsa
        _cd=self.cd
        _money_market=self.money_market
        _paypal=self.paypal
        _prepaid=self.prepaid
        _cash_management=self.cash_management
        _ebt=self.ebt
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"checking={_checking!s}, "
            f"savings={_savings!s}, "
            f"hsa={_hsa!s}, "
            f"cd={_cd!s}, "
            f"money_market={_money_market!s}, "
            f"paypal={_paypal!s}, "
            f"prepaid={_prepaid!s}, "
            f"cash_management={_cash_management!s}, "
            f"ebt={_ebt!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
