"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.earnings_total import EarningsTotal


class Earnings(object):
    """Implementation of the 'Earnings' model.

    An object representing both a breakdown of earnings on a paystub and the total
    earnings.

    Attributes:
        subtotals (List[EarningsTotal]): The model property of type
            List[EarningsTotal].
        totals (List[EarningsTotal]): The model property of type List[EarningsTotal].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "subtotals": "subtotals",
        "totals": "totals",
    }

    _optionals = [
        "subtotals",
        "totals",
    ]

    def __init__(
        self,
        subtotals=APIHelper.SKIP,
        totals=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Earnings instance."""
        # Initialize members of the class
        if subtotals is not APIHelper.SKIP:
            self.subtotals = subtotals
        if totals is not APIHelper.SKIP:
            self.totals = totals

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        subtotals = None
        if dictionary.get("subtotals") is not None:
            subtotals = [
                EarningsTotal.from_dictionary(x)
                    for x in dictionary.get("subtotals")
            ]
        else:
            subtotals = APIHelper.SKIP
        totals = None
        if dictionary.get("totals") is not None:
            totals = [
                EarningsTotal.from_dictionary(x)
                    for x in dictionary.get("totals")
            ]
        else:
            totals = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(subtotals,
                   totals,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _subtotals=(
            self.subtotals
            if hasattr(self, "subtotals")
            else None
        )
        _totals=(
            self.totals
            if hasattr(self, "totals")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"subtotals={_subtotals!r}, "
            f"totals={_totals!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _subtotals=(
            self.subtotals
            if hasattr(self, "subtotals")
            else None
        )
        _totals=(
            self.totals
            if hasattr(self, "totals")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"subtotals={_subtotals!s}, "
            f"totals={_totals!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
