"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from plaid.api_helper import APIHelper
from plaid.models.pay import Pay


class EmploymentDetails(object):
    """Implementation of the 'EmploymentDetails' model.

    An object representing employment details found on a paystub.

    Attributes:
        annual_salary (Pay): An object representing a monetary amount.
        hire_date (date): Date on which the employee was hired, in the YYYY-MM-DD
            format.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "annual_salary": "annual_salary",
        "hire_date": "hire_date",
    }

    _optionals = [
        "annual_salary",
        "hire_date",
    ]

    _nullables = [
        "hire_date",
    ]

    def __init__(
        self,
        annual_salary=APIHelper.SKIP,
        hire_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EmploymentDetails instance."""
        # Initialize members of the class
        if annual_salary is not APIHelper.SKIP:
            self.annual_salary = annual_salary
        if hire_date is not APIHelper.SKIP:
            self.hire_date = hire_date

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        annual_salary =\
            Pay.from_dictionary(
                dictionary.get("annual_salary"))\
                if "annual_salary" in dictionary.keys()\
                else APIHelper.SKIP
        if "hire_date" in dictionary.keys():
            hire_date = dateutil.parser.parse(
                dictionary.get("hire_date")).date()\
                if dictionary.get("hire_date") else None

        else:
            hire_date = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(annual_salary,
                   hire_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _annual_salary=(
            self.annual_salary
            if hasattr(self, "annual_salary")
            else None
        )
        _hire_date=(
            self.hire_date
            if hasattr(self, "hire_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"annual_salary={_annual_salary!r}, "
            f"hire_date={_hire_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _annual_salary=(
            self.annual_salary
            if hasattr(self, "annual_salary")
            else None
        )
        _hire_date=(
            self.hire_date
            if hasattr(self, "hire_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"annual_salary={_annual_salary!s}, "
            f"hire_date={_hire_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
