"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ErrorType(object):
    """Implementation of the 'ErrorType' enum.

    A broad categorization of the error. Safe for programatic use.

    Attributes:
        INVALID_REQUEST: The enum member of type str.
        INVALID_RESULT: The enum member of type str.
        INVALID_INPUT: The enum member of type str.
        INSTITUTION_ERROR: The enum member of type str.
        RATE_LIMIT_EXCEEDED: The enum member of type str.
        API_ERROR: The enum member of type str.
        ITEM_ERROR: The enum member of type str.
        ASSET_REPORT_ERROR: The enum member of type str.
        RECAPTCHA_ERROR: The enum member of type str.
        OAUTH_ERROR: The enum member of type str.
        PAYMENT_ERROR: The enum member of type str.
        BANK_TRANSFER_ERROR: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    INVALID_REQUEST = "INVALID_REQUEST"

    INVALID_RESULT = "INVALID_RESULT"

    INVALID_INPUT = "INVALID_INPUT"

    INSTITUTION_ERROR = "INSTITUTION_ERROR"

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    API_ERROR = "API_ERROR"

    ITEM_ERROR = "ITEM_ERROR"

    ASSET_REPORT_ERROR = "ASSET_REPORT_ERROR"

    RECAPTCHA_ERROR = "RECAPTCHA_ERROR"

    OAUTH_ERROR = "OAUTH_ERROR"

    PAYMENT_ERROR = "PAYMENT_ERROR"

    BANK_TRANSFER_ERROR = "BANK_TRANSFER_ERROR"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
