"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class FeeType(object):
    """Implementation of the 'FeeType' model.

    Fees on the account, e.g. commission, bookkeeping, options-related.

    Attributes:
        account_fee (str): Fees paid for account maintenance
        adjustment (str): Increase or decrease in quantity of item
        dividend (str): Inflow of cash from a dividend
        interest (str): Inflow of cash from interest
        interest_receivable (str): Inflow of cash from interest receivable
        long_term_capital_gain (str): Long-term capital gain received as cash
        legal_fee (str): Fees paid for legal charges or services
        management_fee (str): Fees paid for investment management of a mutual fund or
            other pooled investment vehicle
        margin_expense (str): Fees paid for maintaining margin debt
        non_qualified_dividend (str): Inflow of cash from a non-qualified dividend
        non_resident_tax (str): Taxes paid on behalf of the investor for
            non-residency in investment jurisdiction
        qualified_dividend (str): Inflow of cash from a qualified dividend
        return_of_principal (str): Repayment of loan principal
        short_term_capital_gain (str): Short-term capital gain received as cash
        stock_distribution (str): Inflow of stock from a distribution
        tax (str): Taxes paid on behalf of the investor
        tax_withheld (str): Taxes withheld on behalf of the customer
        transfer_fee (str): Fees incurred for transfer of a holding or account
        trust_fee (str): Fees related to adminstration of a trust account
        unqualified_gain (str): Unqualified capital gain received as cash
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_fee": "account fee",
        "adjustment": "adjustment",
        "dividend": "dividend",
        "interest": "interest",
        "interest_receivable": "interest receivable",
        "long_term_capital_gain": "long-term capital gain",
        "legal_fee": "legal fee",
        "management_fee": "management fee",
        "margin_expense": "margin expense",
        "non_qualified_dividend": "non-qualified dividend",
        "non_resident_tax": "non-resident tax",
        "qualified_dividend": "qualified dividend",
        "return_of_principal": "return of principal",
        "short_term_capital_gain": "short-term capital gain",
        "stock_distribution": "stock distribution",
        "tax": "tax",
        "tax_withheld": "tax withheld",
        "transfer_fee": "transfer fee",
        "trust_fee": "trust fee",
        "unqualified_gain": "unqualified gain",
    }

    _optionals = [
        "account_fee",
        "adjustment",
        "dividend",
        "interest",
        "interest_receivable",
        "long_term_capital_gain",
        "legal_fee",
        "management_fee",
        "margin_expense",
        "non_qualified_dividend",
        "non_resident_tax",
        "qualified_dividend",
        "return_of_principal",
        "short_term_capital_gain",
        "stock_distribution",
        "tax",
        "tax_withheld",
        "transfer_fee",
        "trust_fee",
        "unqualified_gain",
    ]

    def __init__(
        self,
        account_fee=APIHelper.SKIP,
        adjustment=APIHelper.SKIP,
        dividend=APIHelper.SKIP,
        interest=APIHelper.SKIP,
        interest_receivable=APIHelper.SKIP,
        long_term_capital_gain=APIHelper.SKIP,
        legal_fee=APIHelper.SKIP,
        management_fee=APIHelper.SKIP,
        margin_expense=APIHelper.SKIP,
        non_qualified_dividend=APIHelper.SKIP,
        non_resident_tax=APIHelper.SKIP,
        qualified_dividend=APIHelper.SKIP,
        return_of_principal=APIHelper.SKIP,
        short_term_capital_gain=APIHelper.SKIP,
        stock_distribution=APIHelper.SKIP,
        tax=APIHelper.SKIP,
        tax_withheld=APIHelper.SKIP,
        transfer_fee=APIHelper.SKIP,
        trust_fee=APIHelper.SKIP,
        unqualified_gain=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a FeeType instance."""
        # Initialize members of the class
        if account_fee is not APIHelper.SKIP:
            self.account_fee = account_fee
        if adjustment is not APIHelper.SKIP:
            self.adjustment = adjustment
        if dividend is not APIHelper.SKIP:
            self.dividend = dividend
        if interest is not APIHelper.SKIP:
            self.interest = interest
        if interest_receivable is not APIHelper.SKIP:
            self.interest_receivable = interest_receivable
        if long_term_capital_gain is not APIHelper.SKIP:
            self.long_term_capital_gain = long_term_capital_gain
        if legal_fee is not APIHelper.SKIP:
            self.legal_fee = legal_fee
        if management_fee is not APIHelper.SKIP:
            self.management_fee = management_fee
        if margin_expense is not APIHelper.SKIP:
            self.margin_expense = margin_expense
        if non_qualified_dividend is not APIHelper.SKIP:
            self.non_qualified_dividend = non_qualified_dividend
        if non_resident_tax is not APIHelper.SKIP:
            self.non_resident_tax = non_resident_tax
        if qualified_dividend is not APIHelper.SKIP:
            self.qualified_dividend = qualified_dividend
        if return_of_principal is not APIHelper.SKIP:
            self.return_of_principal = return_of_principal
        if short_term_capital_gain is not APIHelper.SKIP:
            self.short_term_capital_gain = short_term_capital_gain
        if stock_distribution is not APIHelper.SKIP:
            self.stock_distribution = stock_distribution
        if tax is not APIHelper.SKIP:
            self.tax = tax
        if tax_withheld is not APIHelper.SKIP:
            self.tax_withheld = tax_withheld
        if transfer_fee is not APIHelper.SKIP:
            self.transfer_fee = transfer_fee
        if trust_fee is not APIHelper.SKIP:
            self.trust_fee = trust_fee
        if unqualified_gain is not APIHelper.SKIP:
            self.unqualified_gain = unqualified_gain

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_fee =\
            dictionary.get("account fee")\
            if dictionary.get("account fee")\
                else APIHelper.SKIP
        adjustment =\
            dictionary.get("adjustment")\
            if dictionary.get("adjustment")\
                else APIHelper.SKIP
        dividend =\
            dictionary.get("dividend")\
            if dictionary.get("dividend")\
                else APIHelper.SKIP
        interest =\
            dictionary.get("interest")\
            if dictionary.get("interest")\
                else APIHelper.SKIP
        interest_receivable =\
            dictionary.get("interest receivable")\
            if dictionary.get("interest receivable")\
                else APIHelper.SKIP
        long_term_capital_gain =\
            dictionary.get("long-term capital gain")\
            if dictionary.get("long-term capital gain")\
                else APIHelper.SKIP
        legal_fee =\
            dictionary.get("legal fee")\
            if dictionary.get("legal fee")\
                else APIHelper.SKIP
        management_fee =\
            dictionary.get("management fee")\
            if dictionary.get("management fee")\
                else APIHelper.SKIP
        margin_expense =\
            dictionary.get("margin expense")\
            if dictionary.get("margin expense")\
                else APIHelper.SKIP
        non_qualified_dividend =\
            dictionary.get("non-qualified dividend")\
            if dictionary.get("non-qualified dividend")\
                else APIHelper.SKIP
        non_resident_tax =\
            dictionary.get("non-resident tax")\
            if dictionary.get("non-resident tax")\
                else APIHelper.SKIP
        qualified_dividend =\
            dictionary.get("qualified dividend")\
            if dictionary.get("qualified dividend")\
                else APIHelper.SKIP
        return_of_principal =\
            dictionary.get("return of principal")\
            if dictionary.get("return of principal")\
                else APIHelper.SKIP
        short_term_capital_gain =\
            dictionary.get("short-term capital gain")\
            if dictionary.get("short-term capital gain")\
                else APIHelper.SKIP
        stock_distribution =\
            dictionary.get("stock distribution")\
            if dictionary.get("stock distribution")\
                else APIHelper.SKIP
        tax =\
            dictionary.get("tax")\
            if dictionary.get("tax")\
                else APIHelper.SKIP
        tax_withheld =\
            dictionary.get("tax withheld")\
            if dictionary.get("tax withheld")\
                else APIHelper.SKIP
        transfer_fee =\
            dictionary.get("transfer fee")\
            if dictionary.get("transfer fee")\
                else APIHelper.SKIP
        trust_fee =\
            dictionary.get("trust fee")\
            if dictionary.get("trust fee")\
                else APIHelper.SKIP
        unqualified_gain =\
            dictionary.get("unqualified gain")\
            if dictionary.get("unqualified gain")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_fee,
                   adjustment,
                   dividend,
                   interest,
                   interest_receivable,
                   long_term_capital_gain,
                   legal_fee,
                   management_fee,
                   margin_expense,
                   non_qualified_dividend,
                   non_resident_tax,
                   qualified_dividend,
                   return_of_principal,
                   short_term_capital_gain,
                   stock_distribution,
                   tax,
                   tax_withheld,
                   transfer_fee,
                   trust_fee,
                   unqualified_gain,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_fee=(
            self.account_fee
            if hasattr(self, "account_fee")
            else None
        )
        _adjustment=(
            self.adjustment
            if hasattr(self, "adjustment")
            else None
        )
        _dividend=(
            self.dividend
            if hasattr(self, "dividend")
            else None
        )
        _interest=(
            self.interest
            if hasattr(self, "interest")
            else None
        )
        _interest_receivable=(
            self.interest_receivable
            if hasattr(self, "interest_receivable")
            else None
        )
        _long_term_capital_gain=(
            self.long_term_capital_gain
            if hasattr(self, "long_term_capital_gain")
            else None
        )
        _legal_fee=(
            self.legal_fee
            if hasattr(self, "legal_fee")
            else None
        )
        _management_fee=(
            self.management_fee
            if hasattr(self, "management_fee")
            else None
        )
        _margin_expense=(
            self.margin_expense
            if hasattr(self, "margin_expense")
            else None
        )
        _non_qualified_dividend=(
            self.non_qualified_dividend
            if hasattr(self, "non_qualified_dividend")
            else None
        )
        _non_resident_tax=(
            self.non_resident_tax
            if hasattr(self, "non_resident_tax")
            else None
        )
        _qualified_dividend=(
            self.qualified_dividend
            if hasattr(self, "qualified_dividend")
            else None
        )
        _return_of_principal=(
            self.return_of_principal
            if hasattr(self, "return_of_principal")
            else None
        )
        _short_term_capital_gain=(
            self.short_term_capital_gain
            if hasattr(self, "short_term_capital_gain")
            else None
        )
        _stock_distribution=(
            self.stock_distribution
            if hasattr(self, "stock_distribution")
            else None
        )
        _tax=(
            self.tax
            if hasattr(self, "tax")
            else None
        )
        _tax_withheld=(
            self.tax_withheld
            if hasattr(self, "tax_withheld")
            else None
        )
        _transfer_fee=(
            self.transfer_fee
            if hasattr(self, "transfer_fee")
            else None
        )
        _trust_fee=(
            self.trust_fee
            if hasattr(self, "trust_fee")
            else None
        )
        _unqualified_gain=(
            self.unqualified_gain
            if hasattr(self, "unqualified_gain")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_fee={_account_fee!r}, "
            f"adjustment={_adjustment!r}, "
            f"dividend={_dividend!r}, "
            f"interest={_interest!r}, "
            f"interest_receivable={_interest_receivable!r}, "
            f"long_term_capital_gain={_long_term_capital_gain!r}, "
            f"legal_fee={_legal_fee!r}, "
            f"management_fee={_management_fee!r}, "
            f"margin_expense={_margin_expense!r}, "
            f"non_qualified_dividend={_non_qualified_dividend!r}, "
            f"non_resident_tax={_non_resident_tax!r}, "
            f"qualified_dividend={_qualified_dividend!r}, "
            f"return_of_principal={_return_of_principal!r}, "
            f"short_term_capital_gain={_short_term_capital_gain!r}, "
            f"stock_distribution={_stock_distribution!r}, "
            f"tax={_tax!r}, "
            f"tax_withheld={_tax_withheld!r}, "
            f"transfer_fee={_transfer_fee!r}, "
            f"trust_fee={_trust_fee!r}, "
            f"unqualified_gain={_unqualified_gain!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_fee=(
            self.account_fee
            if hasattr(self, "account_fee")
            else None
        )
        _adjustment=(
            self.adjustment
            if hasattr(self, "adjustment")
            else None
        )
        _dividend=(
            self.dividend
            if hasattr(self, "dividend")
            else None
        )
        _interest=(
            self.interest
            if hasattr(self, "interest")
            else None
        )
        _interest_receivable=(
            self.interest_receivable
            if hasattr(self, "interest_receivable")
            else None
        )
        _long_term_capital_gain=(
            self.long_term_capital_gain
            if hasattr(self, "long_term_capital_gain")
            else None
        )
        _legal_fee=(
            self.legal_fee
            if hasattr(self, "legal_fee")
            else None
        )
        _management_fee=(
            self.management_fee
            if hasattr(self, "management_fee")
            else None
        )
        _margin_expense=(
            self.margin_expense
            if hasattr(self, "margin_expense")
            else None
        )
        _non_qualified_dividend=(
            self.non_qualified_dividend
            if hasattr(self, "non_qualified_dividend")
            else None
        )
        _non_resident_tax=(
            self.non_resident_tax
            if hasattr(self, "non_resident_tax")
            else None
        )
        _qualified_dividend=(
            self.qualified_dividend
            if hasattr(self, "qualified_dividend")
            else None
        )
        _return_of_principal=(
            self.return_of_principal
            if hasattr(self, "return_of_principal")
            else None
        )
        _short_term_capital_gain=(
            self.short_term_capital_gain
            if hasattr(self, "short_term_capital_gain")
            else None
        )
        _stock_distribution=(
            self.stock_distribution
            if hasattr(self, "stock_distribution")
            else None
        )
        _tax=(
            self.tax
            if hasattr(self, "tax")
            else None
        )
        _tax_withheld=(
            self.tax_withheld
            if hasattr(self, "tax_withheld")
            else None
        )
        _transfer_fee=(
            self.transfer_fee
            if hasattr(self, "transfer_fee")
            else None
        )
        _trust_fee=(
            self.trust_fee
            if hasattr(self, "trust_fee")
            else None
        )
        _unqualified_gain=(
            self.unqualified_gain
            if hasattr(self, "unqualified_gain")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_fee={_account_fee!s}, "
            f"adjustment={_adjustment!s}, "
            f"dividend={_dividend!s}, "
            f"interest={_interest!s}, "
            f"interest_receivable={_interest_receivable!s}, "
            f"long_term_capital_gain={_long_term_capital_gain!s}, "
            f"legal_fee={_legal_fee!s}, "
            f"management_fee={_management_fee!s}, "
            f"margin_expense={_margin_expense!s}, "
            f"non_qualified_dividend={_non_qualified_dividend!s}, "
            f"non_resident_tax={_non_resident_tax!s}, "
            f"qualified_dividend={_qualified_dividend!s}, "
            f"return_of_principal={_return_of_principal!s}, "
            f"short_term_capital_gain={_short_term_capital_gain!s}, "
            f"stock_distribution={_stock_distribution!s}, "
            f"tax={_tax!s}, "
            f"tax_withheld={_tax_withheld!s}, "
            f"transfer_fee={_transfer_fee!s}, "
            f"trust_fee={_trust_fee!s}, "
            f"unqualified_gain={_unqualified_gain!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
