"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.error import Error


class HistoricalUpdateWebhook(object):
    """Implementation of the 'HistoricalUpdateWebhook' model.

    Fired when an Item's historical transaction pull is completed and Plaid has
    prepared as much historical transaction data as possible for the Item. Once this
    webhook has been fired, transaction data beyond the most recent 30 days can be
    fetched for the Item. If [Account Select
    v2](https://plaid.com/docs/link/customization/#account-select) is enabled, this
    webhook will also be fired if account selections for the Item are updated, with
    `num_transactions` set to the number of net new transactions pulled after the
    account selection update.

    Attributes:
        webhook_type (str): `TRANSACTIONS`
        webhook_code (str): `HISTORICAL_UPDATE`
        error (Error): We use standard HTTP response codes for success and failure
            notifications, and our errors are further classified by `error_type`. In
            general, 200 HTTP codes correspond to success, 40X codes are for
            developer- or user-related failures, and 50X codes are for Plaid-related
            issues.  Error fields will be `null` if no error has occurred.
        new_transactions (float): The number of new, unfetched transactions available
        item_id (str): The `item_id` of the Item associated with this webhook,
            warning, or error
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "webhook_type": "webhook_type",
        "webhook_code": "webhook_code",
        "new_transactions": "new_transactions",
        "item_id": "item_id",
        "error": "error",
    }

    _optionals = [
        "error",
    ]

    def __init__(
        self,
        webhook_type=None,
        webhook_code=None,
        new_transactions=None,
        item_id=None,
        error=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a HistoricalUpdateWebhook instance."""
        # Initialize members of the class
        self.webhook_type = webhook_type
        self.webhook_code = webhook_code
        if error is not APIHelper.SKIP:
            self.error = error
        self.new_transactions = new_transactions
        self.item_id = item_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        webhook_type =\
            dictionary.get("webhook_type")\
            if dictionary.get("webhook_type")\
                else None
        webhook_code =\
            dictionary.get("webhook_code")\
            if dictionary.get("webhook_code")\
                else None
        new_transactions =\
            dictionary.get("new_transactions")\
            if dictionary.get("new_transactions")\
                else None
        item_id =\
            dictionary.get("item_id")\
            if dictionary.get("item_id")\
                else None
        error =\
            Error.from_dictionary(
                dictionary.get("error"))\
                if "error" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(webhook_type,
                   webhook_code,
                   new_transactions,
                   item_id,
                   error,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _webhook_type=self.webhook_type
        _webhook_code=self.webhook_code
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _new_transactions=self.new_transactions
        _item_id=self.item_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook_type={_webhook_type!r}, "
            f"webhook_code={_webhook_code!r}, "
            f"error={_error!r}, "
            f"new_transactions={_new_transactions!r}, "
            f"item_id={_item_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _webhook_type=self.webhook_type
        _webhook_code=self.webhook_code
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _new_transactions=self.new_transactions
        _item_id=self.item_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook_type={_webhook_type!s}, "
            f"webhook_code={_webhook_code!s}, "
            f"error={_error!s}, "
            f"new_transactions={_new_transactions!s}, "
            f"item_id={_item_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
