"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from plaid.api_helper import APIHelper


class Holding(object):
    """Implementation of the 'Holding' model.

    A securities holding at an institution.

    Attributes:
        account_id (str): The Plaid `account_id` associated with the holding.
        security_id (str): The Plaid `security_id` associated with the holding.
        institution_price (float): The last price given by the institution for this
            security.
        institution_price_as_of (date): The date at which `institution_price` was
            current.
        institution_value (float): The value of the holding, as reported by the
            institution.
        cost_basis (float): The cost basis of the holding.
        quantity (float): The total quantity of the asset held, as reported by the
            financial institution. If the security is an option, `quantity` will
            reflect the total number of options (typically the number of contracts
            multiplied by 100), not the number of contracts.
        iso_currency_code (str): The ISO-4217 currency code of the holding. Always
            `null` if `unofficial_currency_code` is non-`null`.
        unofficial_currency_code (str): The unofficial currency code associated with
            the holding. Always `null` if `iso_currency_code` is non-`null`.
            Unofficial currency codes are used for currencies that do not have
            official ISO currency codes, such as cryptocurrencies and the currencies
            of certain countries.  See the [currency code
            schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a
            full listing of supported `iso_currency_code`s.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_id": "account_id",
        "security_id": "security_id",
        "institution_price": "institution_price",
        "institution_price_as_of": "institution_price_as_of",
        "institution_value": "institution_value",
        "cost_basis": "cost_basis",
        "quantity": "quantity",
        "iso_currency_code": "iso_currency_code",
        "unofficial_currency_code": "unofficial_currency_code",
    }

    _nullables = [
        "institution_price_as_of",
        "cost_basis",
        "iso_currency_code",
        "unofficial_currency_code",
    ]

    def __init__(
        self,
        account_id=None,
        security_id=None,
        institution_price=None,
        institution_price_as_of=None,
        institution_value=None,
        cost_basis=None,
        quantity=None,
        iso_currency_code=None,
        unofficial_currency_code=None,
        additional_properties=None):
        """Initialize a Holding instance."""
        # Initialize members of the class
        self.account_id = account_id
        self.security_id = security_id
        self.institution_price = institution_price
        self.institution_price_as_of = institution_price_as_of
        self.institution_value = institution_value
        self.cost_basis = cost_basis
        self.quantity = quantity
        self.iso_currency_code = iso_currency_code
        self.unofficial_currency_code = unofficial_currency_code

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_id =\
            dictionary.get("account_id")\
            if dictionary.get("account_id")\
                else None
        security_id =\
            dictionary.get("security_id")\
            if dictionary.get("security_id")\
                else None
        institution_price =\
            dictionary.get("institution_price")\
            if dictionary.get("institution_price")\
                else None
        institution_price_as_of = dateutil.parser.parse(
            dictionary.get("institution_price_as_of")).date()\
            if dictionary.get("institution_price_as_of") else None
        institution_value =\
            dictionary.get("institution_value")\
            if dictionary.get("institution_value")\
                else None
        cost_basis =\
            dictionary.get("cost_basis")\
            if dictionary.get("cost_basis")\
                else None
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else None
        iso_currency_code =\
            dictionary.get("iso_currency_code")\
            if dictionary.get("iso_currency_code")\
                else None
        unofficial_currency_code =\
            dictionary.get("unofficial_currency_code")\
            if dictionary.get("unofficial_currency_code")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_id,
                   security_id,
                   institution_price,
                   institution_price_as_of,
                   institution_value,
                   cost_basis,
                   quantity,
                   iso_currency_code,
                   unofficial_currency_code,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_id=self.account_id
        _security_id=self.security_id
        _institution_price=self.institution_price
        _institution_price_as_of=self.institution_price_as_of
        _institution_value=self.institution_value
        _cost_basis=self.cost_basis
        _quantity=self.quantity
        _iso_currency_code=self.iso_currency_code
        _unofficial_currency_code=self.unofficial_currency_code
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_id={_account_id!r}, "
            f"security_id={_security_id!r}, "
            f"institution_price={_institution_price!r}, "
            f"institution_price_as_of={_institution_price_as_of!r}, "
            f"institution_value={_institution_value!r}, "
            f"cost_basis={_cost_basis!r}, "
            f"quantity={_quantity!r}, "
            f"iso_currency_code={_iso_currency_code!r}, "
            f"unofficial_currency_code={_unofficial_currency_code!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_id=self.account_id
        _security_id=self.security_id
        _institution_price=self.institution_price
        _institution_price_as_of=self.institution_price_as_of
        _institution_value=self.institution_value
        _cost_basis=self.cost_basis
        _quantity=self.quantity
        _iso_currency_code=self.iso_currency_code
        _unofficial_currency_code=self.unofficial_currency_code
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_id={_account_id!s}, "
            f"security_id={_security_id!s}, "
            f"institution_price={_institution_price!s}, "
            f"institution_price_as_of={_institution_price_as_of!s}, "
            f"institution_value={_institution_value!s}, "
            f"cost_basis={_cost_basis!s}, "
            f"quantity={_quantity!s}, "
            f"iso_currency_code={_iso_currency_code!s}, "
            f"unofficial_currency_code={_unofficial_currency_code!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
