"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class IncidentUpdate(object):
    """Implementation of the 'IncidentUpdate' model.

    Attributes:
        description (str): The content of the update.
        status (Status1): The status of the incident.
        updated_date (datetime): The date when the update was published, in [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) format, e.g.
            `"2020-10-30T15:26:48Z"`.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "description": "description",
        "status": "status",
        "updated_date": "updated_date",
    }

    _optionals = [
        "description",
        "status",
        "updated_date",
    ]

    def __init__(
        self,
        description=APIHelper.SKIP,
        status=APIHelper.SKIP,
        updated_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a IncidentUpdate instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if status is not APIHelper.SKIP:
            self.status = status
        if updated_date is not APIHelper.SKIP:
            self.updated_date =\
                 APIHelper.apply_datetime_converter(
                updated_date, APIHelper.RFC3339DateTime)\
                 if updated_date else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        updated_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_date")).datetime\
            if dictionary.get("updated_date") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(description,
                   status,
                   updated_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _updated_date=(
            self.updated_date
            if hasattr(self, "updated_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"status={_status!r}, "
            f"updated_date={_updated_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _updated_date=(
            self.updated_date
            if hasattr(self, "updated_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"status={_status!s}, "
            f"updated_date={_updated_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
