"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.address_data_1 import AddressData1


class IncomeVerificationPrecheckUser(object):
    """Implementation of the 'IncomeVerificationPrecheckUser' model.

    Attributes:
        first_name (str): The user's first name
        last_name (str): The user's last name
        email_address (str): The user's email address
        home_address (AddressData1): Data about the components comprising an address.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first_name": "first_name",
        "last_name": "last_name",
        "email_address": "email_address",
        "home_address": "home_address",
    }

    _optionals = [
        "first_name",
        "last_name",
        "email_address",
        "home_address",
    ]

    _nullables = [
        "first_name",
        "last_name",
        "email_address",
    ]

    def __init__(
        self,
        first_name=APIHelper.SKIP,
        last_name=APIHelper.SKIP,
        email_address=APIHelper.SKIP,
        home_address=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a IncomeVerificationPrecheckUser instance."""
        # Initialize members of the class
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name
        if last_name is not APIHelper.SKIP:
            self.last_name = last_name
        if email_address is not APIHelper.SKIP:
            self.email_address = email_address
        if home_address is not APIHelper.SKIP:
            self.home_address = home_address

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        first_name =\
            dictionary.get("first_name")\
            if "first_name" in dictionary.keys()\
                else APIHelper.SKIP
        last_name =\
            dictionary.get("last_name")\
            if "last_name" in dictionary.keys()\
                else APIHelper.SKIP
        email_address =\
            dictionary.get("email_address")\
            if "email_address" in dictionary.keys()\
                else APIHelper.SKIP
        home_address =\
            AddressData1.from_dictionary(
                dictionary.get("home_address"))\
                if "home_address" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(first_name,
                   last_name,
                   email_address,
                   home_address,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _email_address=(
            self.email_address
            if hasattr(self, "email_address")
            else None
        )
        _home_address=(
            self.home_address
            if hasattr(self, "home_address")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"first_name={_first_name!r}, "
            f"last_name={_last_name!r}, "
            f"email_address={_email_address!r}, "
            f"home_address={_home_address!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _email_address=(
            self.email_address
            if hasattr(self, "email_address")
            else None
        )
        _home_address=(
            self.home_address
            if hasattr(self, "home_address")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"first_name={_first_name!s}, "
            f"last_name={_last_name!s}, "
            f"email_address={_email_address!s}, "
            f"home_address={_home_address!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
