"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.error import Error
from plaid.models.paystub import Paystub


class IncomeVerificationPaystubGetResponse(object):
    """Implementation of the 'IncomeVerificationPaystubGetResponse' model.

    IncomeVerificationPaystubGetResponse defines the response schema for
    `/income/verification/paystub/get`.

    Attributes:
        paystub (Paystub): An object representing data extracted from the end user's
            paystub.
        error (Error): We use standard HTTP response codes for success and failure
            notifications, and our errors are further classified by `error_type`. In
            general, 200 HTTP codes correspond to success, 40X codes are for
            developer- or user-related failures, and 50X codes are for Plaid-related
            issues.  Error fields will be `null` if no error has occurred.
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "paystub": "paystub",
        "request_id": "request_id",
        "error": "error",
    }

    _optionals = [
        "error",
    ]

    def __init__(
        self,
        paystub=None,
        request_id=None,
        error=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a IncomeVerificationPaystubGetResponse instance."""
        # Initialize members of the class
        self.paystub = paystub
        if error is not APIHelper.SKIP:
            self.error = error
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        paystub =\
            Paystub.from_dictionary(
                dictionary.get("paystub"))\
                if dictionary.get("paystub") else None
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None
        error =\
            Error.from_dictionary(
                dictionary.get("error"))\
                if "error" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(paystub,
                   request_id,
                   error,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _paystub=self.paystub
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"paystub={_paystub!r}, "
            f"error={_error!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _paystub=self.paystub
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"paystub={_paystub!s}, "
            f"error={_error!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
