"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.document_metadata import DocumentMetadata
from plaid.models.error import Error
from plaid.models.taxform import Taxform


class IncomeVerificationTaxformsGetResponse(object):
    """Implementation of the 'IncomeVerificationTaxformsGetResponse' model.

    IncomeVerificationTaxformsGetResponse defines the response schema for
    `/income/verification/taxforms/get`

    Attributes:
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        taxforms (List[Taxform]): A list of taxforms.
        document_metadata (List[DocumentMetadata]): The model property of type
            List[DocumentMetadata].
        error (Error): We use standard HTTP response codes for success and failure
            notifications, and our errors are further classified by `error_type`. In
            general, 200 HTTP codes correspond to success, 40X codes are for
            developer- or user-related failures, and 50X codes are for Plaid-related
            issues.  Error fields will be `null` if no error has occurred.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "taxforms": "taxforms",
        "document_metadata": "document_metadata",
        "request_id": "request_id",
        "error": "error",
    }

    _optionals = [
        "request_id",
        "error",
    ]

    def __init__(
        self,
        taxforms=None,
        document_metadata=None,
        request_id=APIHelper.SKIP,
        error=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a IncomeVerificationTaxformsGetResponse instance."""
        # Initialize members of the class
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id
        self.taxforms = taxforms
        self.document_metadata = document_metadata
        if error is not APIHelper.SKIP:
            self.error = error

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        taxforms = None
        if dictionary.get("taxforms") is not None:
            taxforms = [
                Taxform.from_dictionary(x)
                    for x in dictionary.get("taxforms")
            ]
        document_metadata = None
        if dictionary.get("document_metadata") is not None:
            document_metadata = [
                DocumentMetadata.from_dictionary(x)
                    for x in dictionary.get("document_metadata")
            ]
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else APIHelper.SKIP
        error =\
            Error.from_dictionary(
                dictionary.get("error"))\
                if "error" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(taxforms,
                   document_metadata,
                   request_id,
                   error,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _taxforms=self.taxforms
        _document_metadata=self.document_metadata
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request_id={_request_id!r}, "
            f"taxforms={_taxforms!r}, "
            f"document_metadata={_document_metadata!r}, "
            f"error={_error!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _taxforms=self.taxforms
        _document_metadata=self.document_metadata
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request_id={_request_id!s}, "
            f"taxforms={_taxforms!s}, "
            f"document_metadata={_document_metadata!s}, "
            f"error={_error!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
