"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class IncomeVerificationPrecheckResponse(object):
    """Implementation of the 'IncomeVerificationPrecheckResponse' model.

    IncomeVerificationPrecheckResponse defines the response schema for
    `/income/verification/precheck`.

    Attributes:
        precheck_id (str): ID of the precheck.
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        confidence (Confidence): The confidence that Plaid can support the user in
            the income verification flow. One of the following:  `"HIGH"`: This
            precheck information submitted is definitively tied to a Plaid-supported
            integration.  "`LOW`": This precheck information submitted is known not
            to be supported by Plaid.  `"UNKNOWN"`: It was not possible to determine
            if the user is supportable with the information passed.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "precheck_id": "precheck_id",
        "request_id": "request_id",
        "confidence": "confidence",
    }

    def __init__(
        self,
        precheck_id=None,
        request_id=None,
        confidence=None,
        additional_properties=None):
        """Initialize a IncomeVerificationPrecheckResponse instance."""
        # Initialize members of the class
        self.precheck_id = precheck_id
        self.request_id = request_id
        self.confidence = confidence

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        precheck_id =\
            dictionary.get("precheck_id")\
            if dictionary.get("precheck_id")\
                else None
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None
        confidence =\
            dictionary.get("confidence")\
            if dictionary.get("confidence")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(precheck_id,
                   request_id,
                   confidence,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _precheck_id=self.precheck_id
        _request_id=self.request_id
        _confidence=self.confidence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"precheck_id={_precheck_id!r}, "
            f"request_id={_request_id!r}, "
            f"confidence={_confidence!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _precheck_id=self.precheck_id
        _request_id=self.request_id
        _confidence=self.confidence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"precheck_id={_precheck_id!s}, "
            f"request_id={_request_id!s}, "
            f"confidence={_confidence!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
