"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.institution import Institution


class InstitutionsGetResponse(object):
    """Implementation of the 'InstitutionsGetResponse' model.

    InstitutionsGetResponse defines the response schema for `/institutions/get`

    Attributes:
        institutions (List[Institution]): A list of Plaid Institution
        total (int): The total number of institutions available via this endpoint
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "institutions": "institutions",
        "total": "total",
        "request_id": "request_id",
    }

    def __init__(
        self,
        institutions=None,
        total=None,
        request_id=None,
        additional_properties=None):
        """Initialize a InstitutionsGetResponse instance."""
        # Initialize members of the class
        self.institutions = institutions
        self.total = total
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        institutions = None
        if dictionary.get("institutions") is not None:
            institutions = [
                Institution.from_dictionary(x)
                    for x in dictionary.get("institutions")
            ]
        total =\
            dictionary.get("total")\
            if dictionary.get("total")\
                else None
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(institutions,
                   total,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _institutions=self.institutions
        _total=self.total
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"institutions={_institutions!r}, "
            f"total={_total!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _institutions=self.institutions
        _total=self.total
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"institutions={_institutions!s}, "
            f"total={_total!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
