"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.health_incident import HealthIncident
from plaid.models.product_status import ProductStatus


class InstitutionStatus(object):
    """Implementation of the 'InstitutionStatus' model.

    The status of an institution is determined by the health of its Item logins,
    Transactions updates, Investments updates, Liabilities updates, Auth requests,
    Balance requests, Identity requests, Investments requests, and Liabilities
    requests. A login attempt is conducted during the initial Item add in Link. If
    there is not enough traffic to accurately calculate an institution's status,
    Plaid will return null rather than potentially inaccurate data.
    Institution status is accessible in the Dashboard and via the API using the
    `/institutions/get_by_id` endpoint with the `include_status` option set to true.
    Note that institution status is not available in the Sandbox environment.

    Attributes:
        item_logins (ProductStatus): A representation of the status health of a
            request type. Auth requests, Balance requests, Identity requests,
            Investments requests, Liabilities requests, Transactions updates,
            Investments updates, Liabilities updates, and Item logins each have their
            own status object.
        transactions_updates (ProductStatus): A representation of the status health
            of a request type. Auth requests, Balance requests, Identity requests,
            Investments requests, Liabilities requests, Transactions updates,
            Investments updates, Liabilities updates, and Item logins each have their
            own status object.
        auth (ProductStatus): A representation of the status health of a request
            type. Auth requests, Balance requests, Identity requests, Investments
            requests, Liabilities requests, Transactions updates, Investments
            updates, Liabilities updates, and Item logins each have their own status
            object.
        balance (ProductStatus): A representation of the status health of a request
            type. Auth requests, Balance requests, Identity requests, Investments
            requests, Liabilities requests, Transactions updates, Investments
            updates, Liabilities updates, and Item logins each have their own status
            object.
        identity (ProductStatus): A representation of the status health of a request
            type. Auth requests, Balance requests, Identity requests, Investments
            requests, Liabilities requests, Transactions updates, Investments
            updates, Liabilities updates, and Item logins each have their own status
            object.
        investments_updates (ProductStatus): A representation of the status health of
            a request type. Auth requests, Balance requests, Identity requests,
            Investments requests, Liabilities requests, Transactions updates,
            Investments updates, Liabilities updates, and Item logins each have their
            own status object.
        liabilities_updates (ProductStatus): A representation of the status health of
            a request type. Auth requests, Balance requests, Identity requests,
            Investments requests, Liabilities requests, Transactions updates,
            Investments updates, Liabilities updates, and Item logins each have their
            own status object.
        liabilities (ProductStatus): A representation of the status health of a
            request type. Auth requests, Balance requests, Identity requests,
            Investments requests, Liabilities requests, Transactions updates,
            Investments updates, Liabilities updates, and Item logins each have their
            own status object.
        investments (ProductStatus): A representation of the status health of a
            request type. Auth requests, Balance requests, Identity requests,
            Investments requests, Liabilities requests, Transactions updates,
            Investments updates, Liabilities updates, and Item logins each have their
            own status object.
        health_incidents (List[HealthIncident]): Details of recent health incidents
            associated with the institution.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "item_logins": "item_logins",
        "transactions_updates": "transactions_updates",
        "auth": "auth",
        "balance": "balance",
        "identity": "identity",
        "investments_updates": "investments_updates",
        "liabilities_updates": "liabilities_updates",
        "liabilities": "liabilities",
        "investments": "investments",
        "health_incidents": "health_incidents",
    }

    _optionals = [
        "liabilities_updates",
        "liabilities",
        "investments",
        "health_incidents",
    ]

    _nullables = [
        "health_incidents",
    ]

    def __init__(
        self,
        item_logins=None,
        transactions_updates=None,
        auth=None,
        balance=None,
        identity=None,
        investments_updates=None,
        liabilities_updates=APIHelper.SKIP,
        liabilities=APIHelper.SKIP,
        investments=APIHelper.SKIP,
        health_incidents=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a InstitutionStatus instance."""
        # Initialize members of the class
        self.item_logins = item_logins
        self.transactions_updates = transactions_updates
        self.auth = auth
        self.balance = balance
        self.identity = identity
        self.investments_updates = investments_updates
        if liabilities_updates is not APIHelper.SKIP:
            self.liabilities_updates = liabilities_updates
        if liabilities is not APIHelper.SKIP:
            self.liabilities = liabilities
        if investments is not APIHelper.SKIP:
            self.investments = investments
        if health_incidents is not APIHelper.SKIP:
            self.health_incidents = health_incidents

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        item_logins =\
            ProductStatus.from_dictionary(
                dictionary.get("item_logins"))\
                if dictionary.get("item_logins") else None
        transactions_updates =\
            ProductStatus.from_dictionary(
                dictionary.get("transactions_updates"))\
                if dictionary.get("transactions_updates") else None
        auth =\
            ProductStatus.from_dictionary(
                dictionary.get("auth"))\
                if dictionary.get("auth") else None
        balance =\
            ProductStatus.from_dictionary(
                dictionary.get("balance"))\
                if dictionary.get("balance") else None
        identity =\
            ProductStatus.from_dictionary(
                dictionary.get("identity"))\
                if dictionary.get("identity") else None
        investments_updates =\
            ProductStatus.from_dictionary(
                dictionary.get("investments_updates"))\
                if dictionary.get("investments_updates") else None
        liabilities_updates =\
            ProductStatus.from_dictionary(
                dictionary.get("liabilities_updates"))\
                if "liabilities_updates" in dictionary.keys()\
                else APIHelper.SKIP
        liabilities =\
            ProductStatus.from_dictionary(
                dictionary.get("liabilities"))\
                if "liabilities" in dictionary.keys()\
                else APIHelper.SKIP
        investments =\
            ProductStatus.from_dictionary(
                dictionary.get("investments"))\
                if "investments" in dictionary.keys()\
                else APIHelper.SKIP
        if "health_incidents" in dictionary.keys():
            health_incidents = [
                HealthIncident.from_dictionary(x)
                for x in dictionary.get("health_incidents")
            ] if dictionary.get("health_incidents") else None
        else:
            health_incidents = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(item_logins,
                   transactions_updates,
                   auth,
                   balance,
                   identity,
                   investments_updates,
                   liabilities_updates,
                   liabilities,
                   investments,
                   health_incidents,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _item_logins=self.item_logins
        _transactions_updates=self.transactions_updates
        _auth=self.auth
        _balance=self.balance
        _identity=self.identity
        _investments_updates=self.investments_updates
        _liabilities_updates=(
            self.liabilities_updates
            if hasattr(self, "liabilities_updates")
            else None
        )
        _liabilities=(
            self.liabilities
            if hasattr(self, "liabilities")
            else None
        )
        _investments=(
            self.investments
            if hasattr(self, "investments")
            else None
        )
        _health_incidents=(
            self.health_incidents
            if hasattr(self, "health_incidents")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"item_logins={_item_logins!r}, "
            f"transactions_updates={_transactions_updates!r}, "
            f"auth={_auth!r}, "
            f"balance={_balance!r}, "
            f"identity={_identity!r}, "
            f"investments_updates={_investments_updates!r}, "
            f"liabilities_updates={_liabilities_updates!r}, "
            f"liabilities={_liabilities!r}, "
            f"investments={_investments!r}, "
            f"health_incidents={_health_incidents!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _item_logins=self.item_logins
        _transactions_updates=self.transactions_updates
        _auth=self.auth
        _balance=self.balance
        _identity=self.identity
        _investments_updates=self.investments_updates
        _liabilities_updates=(
            self.liabilities_updates
            if hasattr(self, "liabilities_updates")
            else None
        )
        _liabilities=(
            self.liabilities
            if hasattr(self, "liabilities")
            else None
        )
        _investments=(
            self.investments
            if hasattr(self, "investments")
            else None
        )
        _health_incidents=(
            self.health_incidents
            if hasattr(self, "health_incidents")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"item_logins={_item_logins!s}, "
            f"transactions_updates={_transactions_updates!s}, "
            f"auth={_auth!s}, "
            f"balance={_balance!s}, "
            f"identity={_identity!s}, "
            f"investments_updates={_investments_updates!s}, "
            f"liabilities_updates={_liabilities_updates!s}, "
            f"liabilities={_liabilities!s}, "
            f"investments={_investments!s}, "
            f"health_incidents={_health_incidents!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
