"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from plaid.api_helper import APIHelper


class InvestmentTransaction(object):
    """Implementation of the 'InvestmentTransaction' model.

    A transaction within an investment account.

    Attributes:
        investment_transaction_id (str): The ID of the Investment transaction, unique
            across all Plaid transactions. Like all Plaid identifiers, the
            `investment_transaction_id` is case sensitive.
        cancel_transaction_id (str): A legacy field formerly used internally by Plaid
            to identify certain canceled transactions.
        account_id (str): The `account_id` of the account against which this
            transaction posted.
        security_id (str): The `security_id` to which this transaction is related.
        date (date): The [ISO 8601](https://wikipedia.org/wiki/ISO_8601) posting date
            for the transaction, or transacted date for pending transactions.
        name (str): The institution’s description of the transaction.
        quantity (float): The number of units of the security involved in this
            transaction.
        amount (float): The complete value of the transaction. Positive values when
            cash is debited, e.g. purchases of stock; negative values when cash is
            credited, e.g. sales of stock. Treatment remains the same for cash-only
            movements unassociated with securities.
        price (float): The price of the security at which this transaction occurred.
        fees (float): The combined value of all fees applied to this transaction
        mtype (Type4): Value is one of the following: `buy`: Buying an investment
            `sell`: Selling an investment `cancel`: A cancellation of a pending
            transaction `cash`: Activity that modifies a cash position `fee`: A fee
            on the account `transfer`: Activity which modifies a position, but not
            through buy/sell activity e.g. options exercise, portfolio transfer  For
            descriptions of possible transaction types and subtypes, see the
            [Investment transaction types
            schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-
            schema).
        subtype (Subtype): For descriptions of possible transaction types and
            subtypes, see the [Investment transaction types
            schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-
            schema).
        iso_currency_code (str): The ISO-4217 currency code of the transaction.
            Always `null` if `unofficial_currency_code` is non-`null`.
        unofficial_currency_code (str): The unofficial currency code associated with
            the holding. Always `null` if `iso_currency_code` is non-`null`.
            Unofficial currency codes are used for currencies that do not have
            official ISO currency codes, such as cryptocurrencies and the currencies
            of certain countries.  See the [currency code
            schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a
            full listing of supported `iso_currency_code`s.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "investment_transaction_id": "investment_transaction_id",
        "account_id": "account_id",
        "security_id": "security_id",
        "date": "date",
        "name": "name",
        "quantity": "quantity",
        "amount": "amount",
        "price": "price",
        "fees": "fees",
        "mtype": "type",
        "subtype": "subtype",
        "iso_currency_code": "iso_currency_code",
        "unofficial_currency_code": "unofficial_currency_code",
        "cancel_transaction_id": "cancel_transaction_id",
    }

    _optionals = [
        "cancel_transaction_id",
    ]

    _nullables = [
        "cancel_transaction_id",
        "security_id",
        "fees",
        "iso_currency_code",
        "unofficial_currency_code",
    ]

    def __init__(
        self,
        investment_transaction_id=None,
        account_id=None,
        security_id=None,
        date=None,
        name=None,
        quantity=None,
        amount=None,
        price=None,
        fees=None,
        mtype=None,
        subtype=None,
        iso_currency_code=None,
        unofficial_currency_code=None,
        cancel_transaction_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a InvestmentTransaction instance."""
        # Initialize members of the class
        self.investment_transaction_id = investment_transaction_id
        if cancel_transaction_id is not APIHelper.SKIP:
            self.cancel_transaction_id = cancel_transaction_id
        self.account_id = account_id
        self.security_id = security_id
        self.date = date
        self.name = name
        self.quantity = quantity
        self.amount = amount
        self.price = price
        self.fees = fees
        self.mtype = mtype
        self.subtype = subtype
        self.iso_currency_code = iso_currency_code
        self.unofficial_currency_code = unofficial_currency_code

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        investment_transaction_id =\
            dictionary.get("investment_transaction_id")\
            if dictionary.get("investment_transaction_id")\
                else None
        account_id =\
            dictionary.get("account_id")\
            if dictionary.get("account_id")\
                else None
        security_id =\
            dictionary.get("security_id")\
            if dictionary.get("security_id")\
                else None
        date = dateutil.parser.parse(
            dictionary.get("date")).date()\
            if dictionary.get("date") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        price =\
            dictionary.get("price")\
            if dictionary.get("price")\
                else None
        fees =\
            dictionary.get("fees")\
            if dictionary.get("fees")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        subtype =\
            dictionary.get("subtype")\
            if dictionary.get("subtype")\
                else None
        iso_currency_code =\
            dictionary.get("iso_currency_code")\
            if dictionary.get("iso_currency_code")\
                else None
        unofficial_currency_code =\
            dictionary.get("unofficial_currency_code")\
            if dictionary.get("unofficial_currency_code")\
                else None
        cancel_transaction_id =\
            dictionary.get("cancel_transaction_id")\
            if "cancel_transaction_id" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(investment_transaction_id,
                   account_id,
                   security_id,
                   date,
                   name,
                   quantity,
                   amount,
                   price,
                   fees,
                   mtype,
                   subtype,
                   iso_currency_code,
                   unofficial_currency_code,
                   cancel_transaction_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _investment_transaction_id=self.investment_transaction_id
        _cancel_transaction_id=(
            self.cancel_transaction_id
            if hasattr(self, "cancel_transaction_id")
            else None
        )
        _account_id=self.account_id
        _security_id=self.security_id
        _date=self.date
        _name=self.name
        _quantity=self.quantity
        _amount=self.amount
        _price=self.price
        _fees=self.fees
        _mtype=self.mtype
        _subtype=self.subtype
        _iso_currency_code=self.iso_currency_code
        _unofficial_currency_code=self.unofficial_currency_code
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"investment_transaction_id={_investment_transaction_id!r}, "
            f"cancel_transaction_id={_cancel_transaction_id!r}, "
            f"account_id={_account_id!r}, "
            f"security_id={_security_id!r}, "
            f"date={_date!r}, "
            f"name={_name!r}, "
            f"quantity={_quantity!r}, "
            f"amount={_amount!r}, "
            f"price={_price!r}, "
            f"fees={_fees!r}, "
            f"mtype={_mtype!r}, "
            f"subtype={_subtype!r}, "
            f"iso_currency_code={_iso_currency_code!r}, "
            f"unofficial_currency_code={_unofficial_currency_code!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _investment_transaction_id=self.investment_transaction_id
        _cancel_transaction_id=(
            self.cancel_transaction_id
            if hasattr(self, "cancel_transaction_id")
            else None
        )
        _account_id=self.account_id
        _security_id=self.security_id
        _date=self.date
        _name=self.name
        _quantity=self.quantity
        _amount=self.amount
        _price=self.price
        _fees=self.fees
        _mtype=self.mtype
        _subtype=self.subtype
        _iso_currency_code=self.iso_currency_code
        _unofficial_currency_code=self.unofficial_currency_code
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"investment_transaction_id={_investment_transaction_id!s}, "
            f"cancel_transaction_id={_cancel_transaction_id!s}, "
            f"account_id={_account_id!s}, "
            f"security_id={_security_id!s}, "
            f"date={_date!s}, "
            f"name={_name!s}, "
            f"quantity={_quantity!s}, "
            f"amount={_amount!s}, "
            f"price={_price!s}, "
            f"fees={_fees!s}, "
            f"mtype={_mtype!s}, "
            f"subtype={_subtype!s}, "
            f"iso_currency_code={_iso_currency_code!s}, "
            f"unofficial_currency_code={_unofficial_currency_code!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
