"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.item_import_request_options import (
    ItemImportRequestOptions,
)
from plaid.models.item_import_request_user_auth import (
    ItemImportRequestUserAuth,
)


class ItemImportRequest(object):
    """Implementation of the 'ItemImportRequest' model.

    ItemImportRequest defines the request schema for `/item/import`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        products (List[Products]): Array of product strings
        user_auth (ItemImportRequestUserAuth): Object of user ID and auth token pair,
            permitting Plaid to aggregate a user’s accounts
        options (ItemImportRequestOptions): An optional object to configure
            `/item/import` request.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "products": "products",
        "user_auth": "user_auth",
        "client_id": "client_id",
        "secret": "secret",
        "options": "options",
    }

    _optionals = [
        "client_id",
        "secret",
        "options",
    ]

    def __init__(
        self,
        products=None,
        user_auth=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        options=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ItemImportRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.products = products
        self.user_auth = user_auth
        if options is not APIHelper.SKIP:
            self.options = options

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        products =\
            dictionary.get("products")\
            if dictionary.get("products")\
                else None
        user_auth =\
            ItemImportRequestUserAuth.from_dictionary(
                dictionary.get("user_auth"))\
                if dictionary.get("user_auth") else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        options =\
            ItemImportRequestOptions.from_dictionary(
                dictionary.get("options"))\
                if "options" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(products,
                   user_auth,
                   client_id,
                   secret,
                   options,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _products=self.products
        _user_auth=self.user_auth
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"products={_products!r}, "
            f"user_auth={_user_auth!r}, "
            f"options={_options!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _products=self.products
        _user_auth=self.user_auth
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"products={_products!s}, "
            f"user_auth={_user_auth!s}, "
            f"options={_options!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
