"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class ItemStatusInvestments(object):
    """Implementation of the 'ItemStatusInvestments' model.

    Information about the last successful and failed investments update for the Item.

    Attributes:
        last_successful_update (datetime): [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) timestamp of the last
            successful investments update for the Item. The status will update each
            time Plaid successfully connects with the institution, regardless of
            whether any new data is available in the update.
        last_failed_update (datetime): [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) timestamp of the last failed
            investments update for the Item. The status will update each time Plaid
            fails an attempt to connect with the institution, regardless of whether
            any new data is available in the update.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "last_successful_update": "last_successful_update",
        "last_failed_update": "last_failed_update",
    }

    _optionals = [
        "last_successful_update",
        "last_failed_update",
    ]

    _nullables = [
        "last_successful_update",
        "last_failed_update",
    ]

    def __init__(
        self,
        last_successful_update=APIHelper.SKIP,
        last_failed_update=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ItemStatusInvestments instance."""
        # Initialize members of the class
        if last_successful_update is not APIHelper.SKIP:
            self.last_successful_update =\
                 APIHelper.apply_datetime_converter(
                last_successful_update, APIHelper.RFC3339DateTime)\
                 if last_successful_update else None
        if last_failed_update is not APIHelper.SKIP:
            self.last_failed_update =\
                 APIHelper.apply_datetime_converter(
                last_failed_update, APIHelper.RFC3339DateTime)\
                 if last_failed_update else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        if "last_successful_update" in dictionary.keys():
            last_successful_update = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("last_successful_update")).datetime\
                if dictionary.get("last_successful_update") else None

        else:
            last_successful_update = APIHelper.SKIP
        if "last_failed_update" in dictionary.keys():
            last_failed_update = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("last_failed_update")).datetime\
                if dictionary.get("last_failed_update") else None

        else:
            last_failed_update = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(last_successful_update,
                   last_failed_update,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _last_successful_update=(
            self.last_successful_update
            if hasattr(self, "last_successful_update")
            else None
        )
        _last_failed_update=(
            self.last_failed_update
            if hasattr(self, "last_failed_update")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"last_successful_update={_last_successful_update!r}, "
            f"last_failed_update={_last_failed_update!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _last_successful_update=(
            self.last_successful_update
            if hasattr(self, "last_successful_update")
            else None
        )
        _last_failed_update=(
            self.last_failed_update
            if hasattr(self, "last_failed_update")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"last_successful_update={_last_successful_update!s}, "
            f"last_failed_update={_last_failed_update!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
