"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class ItemApplicationListUserAuth(object):
    """Implementation of the 'ItemApplicationListUserAuth' model.

    User authentication parameters, for clients making a request without an
    `access_token`. This is only allowed for select clients and will not be supported
    in the future. Most clients should call /item/import to obtain an access token
    before making a request.

    Attributes:
        user_id (str): Account username.
        fi_username_hash (str): Account username hashed by FI.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_id": "user_id",
        "fi_username_hash": "fi_username_hash",
    }

    _optionals = [
        "user_id",
        "fi_username_hash",
    ]

    _nullables = [
        "user_id",
        "fi_username_hash",
    ]

    def __init__(
        self,
        user_id=APIHelper.SKIP,
        fi_username_hash=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ItemApplicationListUserAuth instance."""
        # Initialize members of the class
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id
        if fi_username_hash is not APIHelper.SKIP:
            self.fi_username_hash = fi_username_hash

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        user_id =\
            dictionary.get("user_id")\
            if "user_id" in dictionary.keys()\
                else APIHelper.SKIP
        fi_username_hash =\
            dictionary.get("fi_username_hash")\
            if "fi_username_hash" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(user_id,
                   fi_username_hash,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _fi_username_hash=(
            self.fi_username_hash
            if hasattr(self, "fi_username_hash")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"user_id={_user_id!r}, "
            f"fi_username_hash={_fi_username_hash!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _fi_username_hash=(
            self.fi_username_hash
            if hasattr(self, "fi_username_hash")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"user_id={_user_id!s}, "
            f"fi_username_hash={_fi_username_hash!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
