"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.credit import Credit
from plaid.models.depository import Depository
from plaid.models.investment import Investment
from plaid.models.loan import Loan


class LinkTokenCreateRequestAccountSubtypes(object):
    """Implementation of the 'LinkTokenCreateRequestAccountSubtypes' model.

    By default, Link will only display account types that are compatible with all
    products supplied in the `products` parameter of `/link/token/create`. You can
    further limit the accounts shown in Link by using `account_filters` to specify
    the account subtypes to be shown in Link. Only the specified subtypes will be
    shown. This filtering applies to both the Account Select view (if enabled) and
    the Institution Select view. Institutions that do not support the selected
    subtypes will be omitted from Link. To indicate that all subtypes should be
    shown, use the value `"all"`. If the `account_filters` filter is used, any
    account type for which a filter is not specified will be entirely omitted from
    Link.
    For a full list of valid types and subtypes, see the [Account
    schema](https://plaid.com/docs/api/accounts#accounts-schema).
    For institutions using OAuth, the filter will not affect the list of institutions
    or accounts shown by the bank in the OAuth window.

    Attributes:
        depository (Depository): A filter to apply to `depository`-type accounts
        credit (Credit): A filter to apply to `credit`-type accounts
        loan (Loan): A filter to apply to `loan`-type accounts
        investment (Investment): A filter to apply to `investment`-type accounts
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "depository": "depository",
        "credit": "credit",
        "loan": "loan",
        "investment": "investment",
    }

    _optionals = [
        "depository",
        "credit",
        "loan",
        "investment",
    ]

    def __init__(
        self,
        depository=APIHelper.SKIP,
        credit=APIHelper.SKIP,
        loan=APIHelper.SKIP,
        investment=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a LinkTokenCreateRequestAccountSubtypes instance."""
        # Initialize members of the class
        if depository is not APIHelper.SKIP:
            self.depository = depository
        if credit is not APIHelper.SKIP:
            self.credit = credit
        if loan is not APIHelper.SKIP:
            self.loan = loan
        if investment is not APIHelper.SKIP:
            self.investment = investment

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        depository =\
            Depository.from_dictionary(
                dictionary.get("depository"))\
                if "depository" in dictionary.keys()\
                else APIHelper.SKIP
        credit =\
            Credit.from_dictionary(
                dictionary.get("credit"))\
                if "credit" in dictionary.keys()\
                else APIHelper.SKIP
        loan =\
            Loan.from_dictionary(
                dictionary.get("loan"))\
                if "loan" in dictionary.keys()\
                else APIHelper.SKIP
        investment =\
            Investment.from_dictionary(
                dictionary.get("investment"))\
                if "investment" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(depository,
                   credit,
                   loan,
                   investment,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _depository=(
            self.depository
            if hasattr(self, "depository")
            else None
        )
        _credit=(
            self.credit
            if hasattr(self, "credit")
            else None
        )
        _loan=(
            self.loan
            if hasattr(self, "loan")
            else None
        )
        _investment=(
            self.investment
            if hasattr(self, "investment")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"depository={_depository!r}, "
            f"credit={_credit!r}, "
            f"loan={_loan!r}, "
            f"investment={_investment!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _depository=(
            self.depository
            if hasattr(self, "depository")
            else None
        )
        _credit=(
            self.credit
            if hasattr(self, "credit")
            else None
        )
        _loan=(
            self.loan
            if hasattr(self, "loan")
            else None
        )
        _investment=(
            self.investment
            if hasattr(self, "investment")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"depository={_depository!s}, "
            f"credit={_credit!s}, "
            f"loan={_loan!s}, "
            f"investment={_investment!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
