"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class MortgageInterestRate(object):
    """Implementation of the 'MortgageInterestRate' model.

    Object containing metadata about the interest rate for the mortgage.

    Attributes:
        percentage (float): Percentage value (interest rate of current mortgage, not
            APR) of interest payable on a loan.
        mtype (str): The type of interest charged (fixed or variable).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "percentage": "percentage",
        "mtype": "type",
    }

    _nullables = [
        "percentage",
        "mtype",
    ]

    def __init__(
        self,
        percentage=None,
        mtype=None,
        additional_properties=None):
        """Initialize a MortgageInterestRate instance."""
        # Initialize members of the class
        self.percentage = percentage
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        percentage =\
            dictionary.get("percentage")\
            if dictionary.get("percentage")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(percentage,
                   mtype,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _percentage=self.percentage
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"percentage={_percentage!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _percentage=self.percentage
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"percentage={_percentage!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
