"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class NewPaymentStatus(object):
    """Implementation of the 'NewPaymentStatus' enum.

    The new status of the payment.
    `PAYMENT_STATUS_INPUT_NEEDED`: This is the initial state of all payments. It
    indicates that the payment is waiting on user input to continue processing. A
    payment may re-enter this state later on if further input is needed.
    `PAYMENT_STATUS_PROCESSING`: The payment is currently being processed. The
    payment will automatically exit this state when processing is complete.
    `PAYMENT_STATUS_INITIATED`: The payment has been successfully initiated and is
    considered complete.
    `PAYMENT_STATUS_COMPLETED`: Indicates that the standing order has been
    successfully established. This state is only used for standing orders.
    `PAYMENT_STATUS_INSUFFICIENT_FUNDS`: The payment has failed due to insufficient
    funds.
    `PAYMENT_STATUS_FAILED`: The payment has failed to be initiated. This error is
    retryable once the root cause is resolved.
    `PAYMENT_STATUS_BLOCKED`: The payment has been blocked. This is a retryable error.
    `PAYMENT_STATUS_UNKNOWN`: The payment status is unknown.

    Attributes:
        PAYMENT_STATUS_INPUT_NEEDED: The enum member of type str.
        PAYMENT_STATUS_PROCESSING: The enum member of type str.
        PAYMENT_STATUS_INITIATED: The enum member of type str.
        PAYMENT_STATUS_COMPLETED: The enum member of type str.
        PAYMENT_STATUS_INSUFFICIENT_FUNDS: The enum member of type str.
        PAYMENT_STATUS_FAILED: The enum member of type str.
        PAYMENT_STATUS_BLOCKED: The enum member of type str.
        PAYMENT_STATUS_UNKNOWN: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    PAYMENT_STATUS_INPUT_NEEDED = "PAYMENT_STATUS_INPUT_NEEDED"

    PAYMENT_STATUS_PROCESSING = "PAYMENT_STATUS_PROCESSING"

    PAYMENT_STATUS_INITIATED = "PAYMENT_STATUS_INITIATED"

    PAYMENT_STATUS_COMPLETED = "PAYMENT_STATUS_COMPLETED"

    PAYMENT_STATUS_INSUFFICIENT_FUNDS = "PAYMENT_STATUS_INSUFFICIENT_FUNDS"

    PAYMENT_STATUS_FAILED = "PAYMENT_STATUS_FAILED"

    PAYMENT_STATUS_BLOCKED = "PAYMENT_STATUS_BLOCKED"

    PAYMENT_STATUS_UNKNOWN = "PAYMENT_STATUS_UNKNOWN"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
