"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.address import Address
from plaid.models.email import Email
from plaid.models.phone_number import PhoneNumber


class OwnerOverride(object):
    """Implementation of the 'OwnerOverride' model.

    Data about the owner or owners of an account. Any fields not specified will be
    filled in with default Sandbox information.

    Attributes:
        names (List[str]): A list of names associated with the account by the
            financial institution. These should always be the names of individuals,
            even for business accounts. Note that the same name data will be used for
            all accounts associated with an Item.
        phone_numbers (List[PhoneNumber]): A list of phone numbers associated with
            the account.
        emails (List[Email]): A list of email addresses associated with the account.
        addresses (List[Address]): Data about the various addresses associated with
            the account.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "names": "names",
        "phone_numbers": "phone_numbers",
        "emails": "emails",
        "addresses": "addresses",
    }

    def __init__(
        self,
        names=None,
        phone_numbers=None,
        emails=None,
        addresses=None,
        additional_properties=None):
        """Initialize a OwnerOverride instance."""
        # Initialize members of the class
        self.names = names
        self.phone_numbers = phone_numbers
        self.emails = emails
        self.addresses = addresses

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        names =\
            dictionary.get("names")\
            if dictionary.get("names")\
                else None
        phone_numbers = None
        if dictionary.get("phone_numbers") is not None:
            phone_numbers = [
                PhoneNumber.from_dictionary(x)
                    for x in dictionary.get("phone_numbers")
            ]
        emails = None
        if dictionary.get("emails") is not None:
            emails = [
                Email.from_dictionary(x)
                    for x in dictionary.get("emails")
            ]
        addresses = None
        if dictionary.get("addresses") is not None:
            addresses = [
                Address.from_dictionary(x)
                    for x in dictionary.get("addresses")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(names,
                   phone_numbers,
                   emails,
                   addresses,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _names=self.names
        _phone_numbers=self.phone_numbers
        _emails=self.emails
        _addresses=self.addresses
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"names={_names!r}, "
            f"phone_numbers={_phone_numbers!r}, "
            f"emails={_emails!r}, "
            f"addresses={_addresses!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _names=self.names
        _phone_numbers=self.phone_numbers
        _emails=self.emails
        _addresses=self.addresses
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"names={_names!s}, "
            f"phone_numbers={_phone_numbers!s}, "
            f"emails={_emails!s}, "
            f"addresses={_addresses!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
