"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.payment_initiation_standing_order_metadata import (
    PaymentInitiationStandingOrderMetadata,
)


class PaymentInitiationMetadata(object):
    """Implementation of the 'PaymentInitiationMetadata' model.

    Metadata that captures what specific payment configurations an institution
    supports when making Payment Initiation requests.

    Attributes:
        supports_international_payments (bool): Indicates whether the institution
            supports payments from a different country.
        maximum_payment_amount (Dict[str, str]): A mapping of currency to maximum
            payment amount (denominated in the smallest unit of currency) supported
            by the insitution.  Example: `{"GBP": "10000"}`
        supports_refund_details (bool): Indicates whether the institution supports
            returning refund details when initiating a payment.
        standing_order_metadata (PaymentInitiationStandingOrderMetadata): Metadata
            specifically related to valid Payment Initiation standing order
            configurations for the institution.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "supports_international_payments": "supports_international_payments",
        "maximum_payment_amount": "maximum_payment_amount",
        "supports_refund_details": "supports_refund_details",
        "standing_order_metadata": "standing_order_metadata",
    }

    def __init__(
        self,
        supports_international_payments=None,
        maximum_payment_amount=None,
        supports_refund_details=None,
        standing_order_metadata=None,
        additional_properties=None):
        """Initialize a PaymentInitiationMetadata instance."""
        # Initialize members of the class
        self.supports_international_payments = supports_international_payments
        self.maximum_payment_amount = maximum_payment_amount
        self.supports_refund_details = supports_refund_details
        self.standing_order_metadata = standing_order_metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        supports_international_payments =\
            dictionary.get("supports_international_payments")\
            if "supports_international_payments" in dictionary.keys()\
                else None
        maximum_payment_amount =\
            dictionary.get("maximum_payment_amount")\
            if dictionary.get("maximum_payment_amount")\
                else None
        supports_refund_details =\
            dictionary.get("supports_refund_details")\
            if "supports_refund_details" in dictionary.keys()\
                else None
        standing_order_metadata =\
            PaymentInitiationStandingOrderMetadata.from_dictionary(
                dictionary.get("standing_order_metadata"))\
                if dictionary.get("standing_order_metadata") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(supports_international_payments,
                   maximum_payment_amount,
                   supports_refund_details,
                   standing_order_metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _supports_international_payments=self.supports_international_payments
        _maximum_payment_amount=self.maximum_payment_amount
        _supports_refund_details=self.supports_refund_details
        _standing_order_metadata=self.standing_order_metadata
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"supports_international_payments={_supports_international_payments!r}, "
            f"maximum_payment_amount={_maximum_payment_amount!r}, "
            f"supports_refund_details={_supports_refund_details!r}, "
            f"standing_order_metadata={_standing_order_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _supports_international_payments=self.supports_international_payments
        _maximum_payment_amount=self.maximum_payment_amount
        _supports_refund_details=self.supports_refund_details
        _standing_order_metadata=self.standing_order_metadata
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"supports_international_payments={_supports_international_payments!s}, "
            f"maximum_payment_amount={_maximum_payment_amount!s}, "
            f"supports_refund_details={_supports_refund_details!s}, "
            f"standing_order_metadata={_standing_order_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
