"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.external_payment_refund_details import (
    ExternalPaymentRefundDetails,
)
from plaid.models.external_payment_schedule_get import (
    ExternalPaymentScheduleGet,
)
from plaid.models.payment_amount import PaymentAmount
from plaid.models.payment_initiation_refund import (
    PaymentInitiationRefund,
)
from plaid.models.sender_bacs_nullable import (
    SenderBacsNullable,
)


class PaymentInitiationPaymentGetResponse(object):
    """Implementation of the 'PaymentInitiationPaymentGetResponse' model.

    PaymentInitiationPaymentGetResponse defines the response schema for
    `/payment_initation/payment/get`

    Attributes:
        payment_id (str): The ID of the payment. Like all Plaid identifiers, the
            `payment_id` is case sensitive.
        amount (PaymentAmount): The amount and currency of a payment
        status (Status3): The status of the payment.  `PAYMENT_STATUS_INPUT_NEEDED`:
            This is the initial state of all payments. It indicates that the payment
            is waiting on user input to continue processing. A payment may re-enter
            this state later on if further input is needed.
            `PAYMENT_STATUS_PROCESSING`: The payment is currently being processed.
            The payment will automatically exit this state when processing is
            complete.  `PAYMENT_STATUS_INITIATED`: The payment has been successfully
            initiated and is considered complete.  `PAYMENT_STATUS_COMPLETED`:
            Indicates that the standing order has been successfully established. This
            state is only used for standing orders.
            `PAYMENT_STATUS_INSUFFICIENT_FUNDS`: The payment has failed due to
            insufficient funds.  `PAYMENT_STATUS_FAILED`: The payment has failed to
            be initiated. This error is retryable once the root cause is resolved.
            `PAYMENT_STATUS_BLOCKED`: The payment has been blocked. This is a
            retryable error.  `PAYMENT_STATUS_UNKNOWN`: The payment status is unknown.
        recipient_id (str): The ID of the recipient
        reference (str): A reference for the payment.
        adjusted_reference (str): The value of the reference sent to the bank after
            adjustment to pass bank validation rules.
        last_status_update (datetime): The date and time of the last time the
            `status` was updated, in IS0 8601 format
        schedule (ExternalPaymentScheduleGet): The schedule that the payment will be
            executed on. If a schedule is provided, the payment is automatically set
            up as a standing order. If no schedule is specified, the payment will be
            executed only once.
        refund_details (ExternalPaymentRefundDetails): The model property of type
            ExternalPaymentRefundDetails.
        bacs (SenderBacsNullable): The model property of type SenderBacsNullable.
        iban (str): The International Bank Account Number (IBAN) for the sender, if
            specified in the `/payment_initiation/payment/create` call.
        initiated_refunds (List[PaymentInitiationRefund]): Initiated refunds
            associated with the payment.
        emi_account_id (str): The EMI (E-Money Institution) account that this payment
            is associated with, if any. This EMI account is used as an intermediary
            account to enable Plaid to reconcile the settlement of funds for Payment
            Initiation requests.
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_id": "payment_id",
        "amount": "amount",
        "status": "status",
        "recipient_id": "recipient_id",
        "reference": "reference",
        "last_status_update": "last_status_update",
        "bacs": "bacs",
        "iban": "iban",
        "request_id": "request_id",
        "adjusted_reference": "adjusted_reference",
        "schedule": "schedule",
        "refund_details": "refund_details",
        "initiated_refunds": "initiated_refunds",
        "emi_account_id": "emi_account_id",
    }

    _optionals = [
        "adjusted_reference",
        "schedule",
        "refund_details",
        "initiated_refunds",
        "emi_account_id",
    ]

    _nullables = [
        "adjusted_reference",
        "iban",
        "emi_account_id",
    ]

    def __init__(
        self,
        payment_id=None,
        amount=None,
        status=None,
        recipient_id=None,
        reference=None,
        last_status_update=None,
        bacs=None,
        iban=None,
        request_id=None,
        adjusted_reference=APIHelper.SKIP,
        schedule=APIHelper.SKIP,
        refund_details=APIHelper.SKIP,
        initiated_refunds=APIHelper.SKIP,
        emi_account_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentInitiationPaymentGetResponse instance."""
        # Initialize members of the class
        self.payment_id = payment_id
        self.amount = amount
        self.status = status
        self.recipient_id = recipient_id
        self.reference = reference
        if adjusted_reference is not APIHelper.SKIP:
            self.adjusted_reference = adjusted_reference
        self.last_status_update =\
             APIHelper.apply_datetime_converter(
            last_status_update, APIHelper.RFC3339DateTime)\
             if last_status_update else None
        if schedule is not APIHelper.SKIP:
            self.schedule = schedule
        if refund_details is not APIHelper.SKIP:
            self.refund_details = refund_details
        self.bacs = bacs
        self.iban = iban
        if initiated_refunds is not APIHelper.SKIP:
            self.initiated_refunds = initiated_refunds
        if emi_account_id is not APIHelper.SKIP:
            self.emi_account_id = emi_account_id
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_id =\
            dictionary.get("payment_id")\
            if dictionary.get("payment_id")\
                else None
        amount =\
            PaymentAmount.from_dictionary(
                dictionary.get("amount"))\
                if dictionary.get("amount") else None
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        recipient_id =\
            dictionary.get("recipient_id")\
            if dictionary.get("recipient_id")\
                else None
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else None
        last_status_update = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("last_status_update")).datetime\
            if dictionary.get("last_status_update") else None
        bacs =\
            SenderBacsNullable.from_dictionary(
                dictionary.get("bacs"))\
                if dictionary.get("bacs") else None
        iban =\
            dictionary.get("iban")\
            if dictionary.get("iban")\
                else None
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None
        adjusted_reference =\
            dictionary.get("adjusted_reference")\
            if "adjusted_reference" in dictionary.keys()\
                else APIHelper.SKIP
        schedule =\
            ExternalPaymentScheduleGet.from_dictionary(
                dictionary.get("schedule"))\
                if "schedule" in dictionary.keys()\
                else APIHelper.SKIP
        refund_details =\
            ExternalPaymentRefundDetails.from_dictionary(
                dictionary.get("refund_details"))\
                if "refund_details" in dictionary.keys()\
                else APIHelper.SKIP
        initiated_refunds = None
        if dictionary.get("initiated_refunds") is not None:
            initiated_refunds = [
                PaymentInitiationRefund.from_dictionary(x)
                    for x in dictionary.get("initiated_refunds")
            ]
        else:
            initiated_refunds = APIHelper.SKIP
        emi_account_id =\
            dictionary.get("emi_account_id")\
            if "emi_account_id" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(payment_id,
                   amount,
                   status,
                   recipient_id,
                   reference,
                   last_status_update,
                   bacs,
                   iban,
                   request_id,
                   adjusted_reference,
                   schedule,
                   refund_details,
                   initiated_refunds,
                   emi_account_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_id=self.payment_id
        _amount=self.amount
        _status=self.status
        _recipient_id=self.recipient_id
        _reference=self.reference
        _adjusted_reference=(
            self.adjusted_reference
            if hasattr(self, "adjusted_reference")
            else None
        )
        _last_status_update=self.last_status_update
        _schedule=(
            self.schedule
            if hasattr(self, "schedule")
            else None
        )
        _refund_details=(
            self.refund_details
            if hasattr(self, "refund_details")
            else None
        )
        _bacs=self.bacs
        _iban=self.iban
        _initiated_refunds=(
            self.initiated_refunds
            if hasattr(self, "initiated_refunds")
            else None
        )
        _emi_account_id=(
            self.emi_account_id
            if hasattr(self, "emi_account_id")
            else None
        )
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"payment_id={_payment_id!r}, "
            f"amount={_amount!r}, "
            f"status={_status!r}, "
            f"recipient_id={_recipient_id!r}, "
            f"reference={_reference!r}, "
            f"adjusted_reference={_adjusted_reference!r}, "
            f"last_status_update={_last_status_update!r}, "
            f"schedule={_schedule!r}, "
            f"refund_details={_refund_details!r}, "
            f"bacs={_bacs!r}, "
            f"iban={_iban!r}, "
            f"initiated_refunds={_initiated_refunds!r}, "
            f"emi_account_id={_emi_account_id!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_id=self.payment_id
        _amount=self.amount
        _status=self.status
        _recipient_id=self.recipient_id
        _reference=self.reference
        _adjusted_reference=(
            self.adjusted_reference
            if hasattr(self, "adjusted_reference")
            else None
        )
        _last_status_update=self.last_status_update
        _schedule=(
            self.schedule
            if hasattr(self, "schedule")
            else None
        )
        _refund_details=(
            self.refund_details
            if hasattr(self, "refund_details")
            else None
        )
        _bacs=self.bacs
        _iban=self.iban
        _initiated_refunds=(
            self.initiated_refunds
            if hasattr(self, "initiated_refunds")
            else None
        )
        _emi_account_id=(
            self.emi_account_id
            if hasattr(self, "emi_account_id")
            else None
        )
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"payment_id={_payment_id!s}, "
            f"amount={_amount!s}, "
            f"status={_status!s}, "
            f"recipient_id={_recipient_id!s}, "
            f"reference={_reference!s}, "
            f"adjusted_reference={_adjusted_reference!s}, "
            f"last_status_update={_last_status_update!s}, "
            f"schedule={_schedule!s}, "
            f"refund_details={_refund_details!s}, "
            f"bacs={_bacs!s}, "
            f"iban={_iban!s}, "
            f"initiated_refunds={_initiated_refunds!s}, "
            f"emi_account_id={_emi_account_id!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
