"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.payment_initiation_optional_restriction_bacs import (
    PaymentInitiationOptionalRestrictionBacs,
)


class PaymentOptions(object):
    """Implementation of the 'PaymentOptions' model.

    Additional payment options

    Attributes:
        request_refund_details (bool): When `true`, Plaid will attempt to request
            refund details from the payee's financial institution.  Support varies
            between financial institutions and will not always be available.  If
            refund details could be retrieved, they will be available in the
            `/payment_initiation/payment/get` response.
        iban (str): The International Bank Account Number (IBAN) for the payer's
            account. If provided, the end user will be able to send payments only
            from the specified bank account.
        bacs (PaymentInitiationOptionalRestrictionBacs): The model property of type
            PaymentInitiationOptionalRestrictionBacs.
        emi_account_id (str): The EMI (E-Money Institution) account that this payment
            is associated with, if any. This EMI account is used as an intermediary
            account to enable Plaid to reconcile the settlement of funds for Payment
            Initiation requests.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_refund_details": "request_refund_details",
        "iban": "iban",
        "bacs": "bacs",
        "emi_account_id": "emi_account_id",
    }

    _optionals = [
        "request_refund_details",
        "iban",
        "bacs",
        "emi_account_id",
    ]

    _nullables = [
        "request_refund_details",
        "iban",
        "emi_account_id",
    ]

    def __init__(
        self,
        request_refund_details=APIHelper.SKIP,
        iban=APIHelper.SKIP,
        bacs=APIHelper.SKIP,
        emi_account_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentOptions instance."""
        # Initialize members of the class
        if request_refund_details is not APIHelper.SKIP:
            self.request_refund_details = request_refund_details
        if iban is not APIHelper.SKIP:
            self.iban = iban
        if bacs is not APIHelper.SKIP:
            self.bacs = bacs
        if emi_account_id is not APIHelper.SKIP:
            self.emi_account_id = emi_account_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        request_refund_details =\
            dictionary.get("request_refund_details")\
            if "request_refund_details" in dictionary.keys()\
                else APIHelper.SKIP
        iban =\
            dictionary.get("iban")\
            if "iban" in dictionary.keys()\
                else APIHelper.SKIP
        bacs =\
            PaymentInitiationOptionalRestrictionBacs.from_dictionary(
                dictionary.get("bacs"))\
                if "bacs" in dictionary.keys()\
                else APIHelper.SKIP
        emi_account_id =\
            dictionary.get("emi_account_id")\
            if "emi_account_id" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(request_refund_details,
                   iban,
                   bacs,
                   emi_account_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _request_refund_details=(
            self.request_refund_details
            if hasattr(self, "request_refund_details")
            else None
        )
        _iban=(
            self.iban
            if hasattr(self, "iban")
            else None
        )
        _bacs=(
            self.bacs
            if hasattr(self, "bacs")
            else None
        )
        _emi_account_id=(
            self.emi_account_id
            if hasattr(self, "emi_account_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request_refund_details={_request_refund_details!r}, "
            f"iban={_iban!r}, "
            f"bacs={_bacs!r}, "
            f"emi_account_id={_emi_account_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _request_refund_details=(
            self.request_refund_details
            if hasattr(self, "request_refund_details")
            else None
        )
        _iban=(
            self.iban
            if hasattr(self, "iban")
            else None
        )
        _bacs=(
            self.bacs
            if hasattr(self, "bacs")
            else None
        )
        _emi_account_id=(
            self.emi_account_id
            if hasattr(self, "emi_account_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"request_refund_details={_request_refund_details!s}, "
            f"iban={_iban!s}, "
            f"bacs={_bacs!s}, "
            f"emi_account_id={_emi_account_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
