"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.payment_initiation_address import (
    PaymentInitiationAddress,
)
from plaid.models.recipient_bacs_nullable import (
    RecipientBacsNullable,
)


class PaymentInitiationRecipientCreateRequest(object):
    """Implementation of the 'PaymentInitiationRecipientCreateRequest' model.

    PaymentInitiationRecipientCreateRequest defines the request schema for
    `/payment_initiation/recipient/create`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        name (str): The name of the recipient
        iban (str): The International Bank Account Number (IBAN) for the recipient.
            If BACS data is not provided, an IBAN is required.
        bacs (RecipientBacsNullable): The model property of type
            RecipientBacsNullable.
        address (PaymentInitiationAddress): The optional address of the payment
            recipient. This object is not currently required to make payments from UK
            institutions and should not be populated, though may be necessary for
            future European expansion.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "client_id": "client_id",
        "secret": "secret",
        "iban": "iban",
        "bacs": "bacs",
        "address": "address",
    }

    _optionals = [
        "client_id",
        "secret",
        "iban",
        "bacs",
        "address",
    ]

    _nullables = [
        "iban",
    ]

    def __init__(
        self,
        name=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        iban=APIHelper.SKIP,
        bacs=APIHelper.SKIP,
        address=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentInitiationRecipientCreateRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.name = name
        if iban is not APIHelper.SKIP:
            self.iban = iban
        if bacs is not APIHelper.SKIP:
            self.bacs = bacs
        if address is not APIHelper.SKIP:
            self.address = address

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        iban =\
            dictionary.get("iban")\
            if "iban" in dictionary.keys()\
                else APIHelper.SKIP
        bacs =\
            RecipientBacsNullable.from_dictionary(
                dictionary.get("bacs"))\
                if "bacs" in dictionary.keys()\
                else APIHelper.SKIP
        address =\
            PaymentInitiationAddress.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   client_id,
                   secret,
                   iban,
                   bacs,
                   address,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _name=self.name
        _iban=(
            self.iban
            if hasattr(self, "iban")
            else None
        )
        _bacs=(
            self.bacs
            if hasattr(self, "bacs")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"name={_name!r}, "
            f"iban={_iban!r}, "
            f"bacs={_bacs!r}, "
            f"address={_address!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _name=self.name
        _iban=(
            self.iban
            if hasattr(self, "iban")
            else None
        )
        _bacs=(
            self.bacs
            if hasattr(self, "bacs")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"name={_name!s}, "
            f"iban={_iban!s}, "
            f"bacs={_bacs!s}, "
            f"address={_address!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
