"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from plaid.api_helper import APIHelper


class PaystubDetails(object):
    """Implementation of the 'PaystubDetails' model.

    An object representing details that can be found on the paystub.

    Attributes:
        pay_period_start_date (date): Beginning date of the pay period on the paystub
            in the 'YYYY-MM-DD' format.
        pay_period_end_date (date): Ending date of the pay period on the paystub in
            the 'YYYY-MM-DD' format.
        pay_date (date): Pay date on the paystub in the 'YYYY-MM-DD' format.
        paystub_provider (str): The name of the payroll provider that generated the
            paystub, e.g. ADP
        pay_frequency (PayFrequency1): The frequency at which the employee is paid.
            Possible values: `MONTHLY`, `BI-WEEKLY`, `WEEKLY`, `SEMI-MONTHLY`.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pay_period_start_date": "pay_period_start_date",
        "pay_period_end_date": "pay_period_end_date",
        "pay_date": "pay_date",
        "paystub_provider": "paystub_provider",
        "pay_frequency": "pay_frequency",
    }

    _optionals = [
        "pay_period_start_date",
        "pay_period_end_date",
        "pay_date",
        "paystub_provider",
        "pay_frequency",
    ]

    _nullables = [
        "pay_period_start_date",
        "pay_period_end_date",
        "pay_date",
        "paystub_provider",
    ]

    def __init__(
        self,
        pay_period_start_date=APIHelper.SKIP,
        pay_period_end_date=APIHelper.SKIP,
        pay_date=APIHelper.SKIP,
        paystub_provider=APIHelper.SKIP,
        pay_frequency=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaystubDetails instance."""
        # Initialize members of the class
        if pay_period_start_date is not APIHelper.SKIP:
            self.pay_period_start_date = pay_period_start_date
        if pay_period_end_date is not APIHelper.SKIP:
            self.pay_period_end_date = pay_period_end_date
        if pay_date is not APIHelper.SKIP:
            self.pay_date = pay_date
        if paystub_provider is not APIHelper.SKIP:
            self.paystub_provider = paystub_provider
        if pay_frequency is not APIHelper.SKIP:
            self.pay_frequency = pay_frequency

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        if "pay_period_start_date" in dictionary.keys():
            pay_period_start_date = dateutil.parser.parse(
                dictionary.get("pay_period_start_date")).date()\
                if dictionary.get("pay_period_start_date") else None

        else:
            pay_period_start_date = APIHelper.SKIP
        if "pay_period_end_date" in dictionary.keys():
            pay_period_end_date = dateutil.parser.parse(
                dictionary.get("pay_period_end_date")).date()\
                if dictionary.get("pay_period_end_date") else None

        else:
            pay_period_end_date = APIHelper.SKIP
        if "pay_date" in dictionary.keys():
            pay_date = dateutil.parser.parse(
                dictionary.get("pay_date")).date()\
                if dictionary.get("pay_date") else None

        else:
            pay_date = APIHelper.SKIP
        paystub_provider =\
            dictionary.get("paystub_provider")\
            if "paystub_provider" in dictionary.keys()\
                else APIHelper.SKIP
        pay_frequency =\
            dictionary.get("pay_frequency")\
            if dictionary.get("pay_frequency")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(pay_period_start_date,
                   pay_period_end_date,
                   pay_date,
                   paystub_provider,
                   pay_frequency,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _pay_period_start_date=(
            self.pay_period_start_date
            if hasattr(self, "pay_period_start_date")
            else None
        )
        _pay_period_end_date=(
            self.pay_period_end_date
            if hasattr(self, "pay_period_end_date")
            else None
        )
        _pay_date=(
            self.pay_date
            if hasattr(self, "pay_date")
            else None
        )
        _paystub_provider=(
            self.paystub_provider
            if hasattr(self, "paystub_provider")
            else None
        )
        _pay_frequency=(
            self.pay_frequency
            if hasattr(self, "pay_frequency")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"pay_period_start_date={_pay_period_start_date!r}, "
            f"pay_period_end_date={_pay_period_end_date!r}, "
            f"pay_date={_pay_date!r}, "
            f"paystub_provider={_paystub_provider!r}, "
            f"pay_frequency={_pay_frequency!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _pay_period_start_date=(
            self.pay_period_start_date
            if hasattr(self, "pay_period_start_date")
            else None
        )
        _pay_period_end_date=(
            self.pay_period_end_date
            if hasattr(self, "pay_period_end_date")
            else None
        )
        _pay_date=(
            self.pay_date
            if hasattr(self, "pay_date")
            else None
        )
        _paystub_provider=(
            self.paystub_provider
            if hasattr(self, "paystub_provider")
            else None
        )
        _pay_frequency=(
            self.pay_frequency
            if hasattr(self, "pay_frequency")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"pay_period_start_date={_pay_period_start_date!s}, "
            f"pay_period_end_date={_pay_period_end_date!s}, "
            f"pay_date={_pay_date!s}, "
            f"paystub_provider={_paystub_provider!s}, "
            f"pay_frequency={_pay_frequency!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
