"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class PendingExpirationWebhook(object):
    """Implementation of the 'PendingExpirationWebhook' model.

    Fired when an Item’s access consent is expiring in 7 days. Some Items have
    explicit expiration times and we try to relay this when possible to reduce
    service disruption. This can be resolved by having the user go through Link’s
    update mode.

    Attributes:
        webhook_type (str): `ITEM`
        webhook_code (str): `PENDING_EXPIRATION`
        item_id (str): The `item_id` of the Item associated with this webhook,
            warning, or error
        consent_expiration_time (datetime): The date and time at which the Item's
            access consent will expire, in [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) format
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "webhook_type": "webhook_type",
        "webhook_code": "webhook_code",
        "item_id": "item_id",
        "consent_expiration_time": "consent_expiration_time",
    }

    def __init__(
        self,
        webhook_type=None,
        webhook_code=None,
        item_id=None,
        consent_expiration_time=None,
        additional_properties=None):
        """Initialize a PendingExpirationWebhook instance."""
        # Initialize members of the class
        self.webhook_type = webhook_type
        self.webhook_code = webhook_code
        self.item_id = item_id
        self.consent_expiration_time =\
             APIHelper.apply_datetime_converter(
            consent_expiration_time, APIHelper.RFC3339DateTime)\
             if consent_expiration_time else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        webhook_type =\
            dictionary.get("webhook_type")\
            if dictionary.get("webhook_type")\
                else None
        webhook_code =\
            dictionary.get("webhook_code")\
            if dictionary.get("webhook_code")\
                else None
        item_id =\
            dictionary.get("item_id")\
            if dictionary.get("item_id")\
                else None
        consent_expiration_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("consent_expiration_time")).datetime\
            if dictionary.get("consent_expiration_time") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(webhook_type,
                   webhook_code,
                   item_id,
                   consent_expiration_time,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _webhook_type=self.webhook_type
        _webhook_code=self.webhook_code
        _item_id=self.item_id
        _consent_expiration_time=self.consent_expiration_time
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook_type={_webhook_type!r}, "
            f"webhook_code={_webhook_code!r}, "
            f"item_id={_item_id!r}, "
            f"consent_expiration_time={_consent_expiration_time!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _webhook_type=self.webhook_type
        _webhook_code=self.webhook_code
        _item_id=self.item_id
        _consent_expiration_time=self.consent_expiration_time
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook_type={_webhook_type!s}, "
            f"webhook_code={_webhook_code!s}, "
            f"item_id={_item_id!s}, "
            f"consent_expiration_time={_consent_expiration_time!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
