"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Processor(object):
    """Implementation of the 'Processor' enum.

    The processor you are integrating with.

    Attributes:
        ACHQ: The enum member of type str.
        ALPACA: The enum member of type str.
        ASTRA: The enum member of type str.
        CHECK: The enum member of type str.
        CHECKBOOK: The enum member of type str.
        CIRCLE: The enum member of type str.
        DRIVEWEALTH: The enum member of type str.
        DWOLLA: The enum member of type str.
        GALILEO: The enum member of type str.
        LITHIC: The enum member of type str.
        MODERN_TREASURY: The enum member of type str.
        MOOV: The enum member of type str.
        OCROLUS: The enum member of type str.
        PRIME_TRUST: The enum member of type str.
        RIZE: The enum member of type str.
        SILA_MONEY: The enum member of type str.
        SVB_API: The enum member of type str.
        TREASURY_PRIME: The enum member of type str.
        UNIT: The enum member of type str.
        VESTA: The enum member of type str.
        VOPAY: The enum member of type str.
        WYRE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    ACHQ = "achq"

    ALPACA = "alpaca"

    ASTRA = "astra"

    CHECK = "check"

    CHECKBOOK = "checkbook"

    CIRCLE = "circle"

    DRIVEWEALTH = "drivewealth"

    DWOLLA = "dwolla"

    GALILEO = "galileo"

    LITHIC = "lithic"

    MODERN_TREASURY = "modern_treasury"

    MOOV = "moov"

    OCROLUS = "ocrolus"

    PRIME_TRUST = "prime_trust"

    RIZE = "rize"

    SILA_MONEY = "sila_money"

    SVB_API = "svb_api"

    TREASURY_PRIME = "treasury_prime"

    UNIT = "unit"

    VESTA = "vesta"

    VOPAY = "vopay"

    WYRE = "wyre"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
