"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class RecaptchaRequiredError(object):
    """Implementation of the 'Recaptcha_RequiredError' model.

    The request was flagged by Plaid's fraud system, and requires additional
    verification to ensure they are not a bot.

    Attributes:
        error_type (str): RECAPTCHA_ERROR
        error_code (str): RECAPTCHA_REQUIRED
        display_message (str): The model property of type str.
        http_code (str): 400
        link_user_experience (str): Your user will be prompted to solve a Google
            reCAPTCHA challenge in the Link Recaptcha pane. If they solve the
            challenge successfully, the user's request is resubmitted and they are
            directed to the next Item creation step.
        common_causes (str): Plaid's fraud system detects abusive traffic and
            considers a variety of parameters throughout Item creation requests. When
            a request is considered risky or possibly fraudulent, Link presents a
            reCAPTCHA for the user to solve.
        troubleshooting_steps (str): Link will automatically guide your user through
            reCAPTCHA verification. As a general rule, we recommend instrumenting
            basic fraud monitoring to detect and protect your website from spam and
            abuse.  If your user cannot verify their session, please submit a Support
            ticket with the following identifiers: `link_session_id` or `request_id`
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error_type": "error_type",
        "error_code": "error_code",
        "display_message": "display_message",
        "http_code": "http_code",
        "link_user_experience": "link_user_experience",
        "common_causes": "common_causes",
        "troubleshooting_steps": "troubleshooting_steps",
    }

    def __init__(
        self,
        error_type=None,
        error_code=None,
        display_message=None,
        http_code=None,
        link_user_experience=None,
        common_causes=None,
        troubleshooting_steps=None,
        additional_properties=None):
        """Initialize a RecaptchaRequiredError instance."""
        # Initialize members of the class
        self.error_type = error_type
        self.error_code = error_code
        self.display_message = display_message
        self.http_code = http_code
        self.link_user_experience = link_user_experience
        self.common_causes = common_causes
        self.troubleshooting_steps = troubleshooting_steps

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        error_type =\
            dictionary.get("error_type")\
            if dictionary.get("error_type")\
                else None
        error_code =\
            dictionary.get("error_code")\
            if dictionary.get("error_code")\
                else None
        display_message =\
            dictionary.get("display_message")\
            if dictionary.get("display_message")\
                else None
        http_code =\
            dictionary.get("http_code")\
            if dictionary.get("http_code")\
                else None
        link_user_experience =\
            dictionary.get("link_user_experience")\
            if dictionary.get("link_user_experience")\
                else None
        common_causes =\
            dictionary.get("common_causes")\
            if dictionary.get("common_causes")\
                else None
        troubleshooting_steps =\
            dictionary.get("troubleshooting_steps")\
            if dictionary.get("troubleshooting_steps")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(error_type,
                   error_code,
                   display_message,
                   http_code,
                   link_user_experience,
                   common_causes,
                   troubleshooting_steps,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _error_type=self.error_type
        _error_code=self.error_code
        _display_message=self.display_message
        _http_code=self.http_code
        _link_user_experience=self.link_user_experience
        _common_causes=self.common_causes
        _troubleshooting_steps=self.troubleshooting_steps
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"error_type={_error_type!r}, "
            f"error_code={_error_code!r}, "
            f"display_message={_display_message!r}, "
            f"http_code={_http_code!r}, "
            f"link_user_experience={_link_user_experience!r}, "
            f"common_causes={_common_causes!r}, "
            f"troubleshooting_steps={_troubleshooting_steps!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _error_type=self.error_type
        _error_code=self.error_code
        _display_message=self.display_message
        _http_code=self.http_code
        _link_user_experience=self.link_user_experience
        _common_causes=self.common_causes
        _troubleshooting_steps=self.troubleshooting_steps
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"error_type={_error_type!s}, "
            f"error_code={_error_code!s}, "
            f"display_message={_display_message!s}, "
            f"http_code={_http_code!s}, "
            f"link_user_experience={_link_user_experience!s}, "
            f"common_causes={_common_causes!s}, "
            f"troubleshooting_steps={_troubleshooting_steps!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
