"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class SandboxIncomeFireWebhookRequest(object):
    """Implementation of the 'SandboxIncomeFireWebhookRequest' model.

    SandboxIncomeFireWebhookRequest defines the request schema for
    `/sandbox/income/fire_webhook`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        income_verification_id (str): The ID of the verification.
        webhook (str): The URL to which the webhook should be sent.
        verification_status (VerificationStatus3):
            `VERIFICATION_STATUS_PROCESSING_COMPLETE`: The income verification status
            processing has completed.  `VERIFICATION_STATUS_DOCUMENT_REJECTED`: The
            documentation uploaded by the end user was recognized as a supported file
            format, but not recognized as a valid paystub.
            `VERIFICATION_STATUS_PROCESSING_FAILED`: A failure occurred when
            attempting to process the verification documentation.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "income_verification_id": "income_verification_id",
        "webhook": "webhook",
        "verification_status": "verification_status",
        "client_id": "client_id",
        "secret": "secret",
    }

    _optionals = [
        "client_id",
        "secret",
    ]

    def __init__(
        self,
        income_verification_id=None,
        webhook=None,
        verification_status=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SandboxIncomeFireWebhookRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.income_verification_id = income_verification_id
        self.webhook = webhook
        self.verification_status = verification_status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        income_verification_id =\
            dictionary.get("income_verification_id")\
            if dictionary.get("income_verification_id")\
                else None
        webhook =\
            dictionary.get("webhook")\
            if dictionary.get("webhook")\
                else None
        verification_status =\
            dictionary.get("verification_status")\
            if dictionary.get("verification_status")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(income_verification_id,
                   webhook,
                   verification_status,
                   client_id,
                   secret,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _income_verification_id=self.income_verification_id
        _webhook=self.webhook
        _verification_status=self.verification_status
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"income_verification_id={_income_verification_id!r}, "
            f"webhook={_webhook!r}, "
            f"verification_status={_verification_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _income_verification_id=self.income_verification_id
        _webhook=self.webhook
        _verification_status=self.verification_status
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"income_verification_id={_income_verification_id!s}, "
            f"webhook={_webhook!s}, "
            f"verification_status={_verification_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
