"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class SandboxPublicTokenCreateResponse(object):
    """Implementation of the 'SandboxPublicTokenCreateResponse' model.

    SandboxPublicTokenCreateResponse defines the response schema for
    `/sandbox/public_token/create`

    Attributes:
        public_token (str): A public token that can be exchanged for an access token
            using `/item/public_token/exchange`
        request_id (str): A unique identifier for the request, which can be used for
            troubleshooting. This identifier, like all Plaid identifiers, is case
            sensitive.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "public_token": "public_token",
        "request_id": "request_id",
    }

    def __init__(
        self,
        public_token=None,
        request_id=None,
        additional_properties=None):
        """Initialize a SandboxPublicTokenCreateResponse instance."""
        # Initialize members of the class
        self.public_token = public_token
        self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        public_token =\
            dictionary.get("public_token")\
            if dictionary.get("public_token")\
                else None
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(public_token,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _public_token=self.public_token
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"public_token={_public_token!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _public_token=self.public_token
        _request_id=self.request_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"public_token={_public_token!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
