"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.sandbox_public_token_create_request_options_transactions import (
    SandboxPublicTokenCreateRequestOptionsTransactions,
)


class SandboxPublicTokenCreateRequestOptions(object):
    """Implementation of the 'SandboxPublicTokenCreateRequestOptions' model.

    An optional set of options to be used when configuring the Item. If specified,
    must not be `null`.

    Attributes:
        webhook (str): Specify a webhook to associate with the new Item.
        override_username (str): Test username to use for the creation of the Sandbox
            Item. Default value is `user_good`.
        override_password (str): Test password to use for the creation of the Sandbox
            Item. Default value is `pass_good`.
        transactions (SandboxPublicTokenCreateRequestOptionsTransactions):
            SandboxPublicTokenCreateRequestOptionsTransactions is an optional set of
            parameters corresponding to transactions options.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "webhook": "webhook",
        "override_username": "override_username",
        "override_password": "override_password",
        "transactions": "transactions",
    }

    _optionals = [
        "webhook",
        "override_username",
        "override_password",
        "transactions",
    ]

    _nullables = [
        "override_username",
        "override_password",
    ]

    def __init__(
        self,
        webhook=APIHelper.SKIP,
        override_username="user_good",
        override_password="pass_good",
        transactions=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SandboxPublicTokenCreateRequestOptions instance."""
        # Initialize members of the class
        if webhook is not APIHelper.SKIP:
            self.webhook = webhook
        self.override_username = override_username
        self.override_password = override_password
        if transactions is not APIHelper.SKIP:
            self.transactions = transactions

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        webhook =\
            dictionary.get("webhook")\
            if dictionary.get("webhook")\
                else APIHelper.SKIP
        override_username =\
            dictionary.get("override_username")\
            if dictionary.get("override_username")\
                else "user_good"
        override_password =\
            dictionary.get("override_password")\
            if dictionary.get("override_password")\
                else "pass_good"
        transactions =\
            SandboxPublicTokenCreateRequestOptionsTransactions.from_dictionary(
                dictionary.get("transactions"))\
                if "transactions" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(webhook,
                   override_username,
                   override_password,
                   transactions,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _override_username=(
            self.override_username
            if hasattr(self, "override_username")
            else None
        )
        _override_password=(
            self.override_password
            if hasattr(self, "override_password")
            else None
        )
        _transactions=(
            self.transactions
            if hasattr(self, "transactions")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook={_webhook!r}, "
            f"override_username={_override_username!r}, "
            f"override_password={_override_password!r}, "
            f"transactions={_transactions!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _override_username=(
            self.override_username
            if hasattr(self, "override_username")
            else None
        )
        _override_password=(
            self.override_password
            if hasattr(self, "override_password")
            else None
        )
        _transactions=(
            self.transactions
            if hasattr(self, "transactions")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"webhook={_webhook!s}, "
            f"override_username={_override_username!s}, "
            f"override_password={_override_password!s}, "
            f"transactions={_transactions!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
