"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.address_data_1 import AddressData1
from plaid.models.signal_person_name import (
    SignalPersonName,
)


class SignalUser(object):
    """Implementation of the 'SignalUser' model.

    Details about the end user initiating the transaction (i.e., the account holder).

    Attributes:
        name (SignalPersonName): The user's legal name
        phone_number (str): The user's phone number, in E.164 format:
            +{countrycode}{number}. For example: "+14151234567"
        email_address (str): The user's email address.
        address (AddressData1): Data about the components comprising an address.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "phone_number": "phone_number",
        "email_address": "email_address",
        "address": "address",
    }

    _optionals = [
        "name",
        "phone_number",
        "email_address",
        "address",
    ]

    _nullables = [
        "phone_number",
        "email_address",
    ]

    def __init__(
        self,
        name=APIHelper.SKIP,
        phone_number=APIHelper.SKIP,
        email_address=APIHelper.SKIP,
        address=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SignalUser instance."""
        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name
        if phone_number is not APIHelper.SKIP:
            self.phone_number = phone_number
        if email_address is not APIHelper.SKIP:
            self.email_address = email_address
        if address is not APIHelper.SKIP:
            self.address = address

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            SignalPersonName.from_dictionary(
                dictionary.get("name"))\
                if "name" in dictionary.keys()\
                else APIHelper.SKIP
        phone_number =\
            dictionary.get("phone_number")\
            if "phone_number" in dictionary.keys()\
                else APIHelper.SKIP
        email_address =\
            dictionary.get("email_address")\
            if "email_address" in dictionary.keys()\
                else APIHelper.SKIP
        address =\
            AddressData1.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   phone_number,
                   email_address,
                   address,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _phone_number=(
            self.phone_number
            if hasattr(self, "phone_number")
            else None
        )
        _email_address=(
            self.email_address
            if hasattr(self, "email_address")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"phone_number={_phone_number!r}, "
            f"email_address={_email_address!r}, "
            f"address={_address!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _phone_number=(
            self.phone_number
            if hasattr(self, "phone_number")
            else None
        )
        _email_address=(
            self.email_address
            if hasattr(self, "email_address")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"phone_number={_phone_number!s}, "
            f"email_address={_email_address!s}, "
            f"address={_address!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
