"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper
from plaid.models.signal_evaluate_device import (
    SignalEvaluateDevice,
)
from plaid.models.signal_user import SignalUser


class SignalEvaluateRequest(object):
    """Implementation of the 'SignalEvaluateRequest' model.

    SignalEvaluateRequest defines the request schema for `/signal/evaluate`

    Attributes:
        client_id (str): Your Plaid API `client_id`. The `client_id` is required and
            may be provided either in the `PLAID-CLIENT-ID` header or as part of a
            request body.
        secret (str): Your Plaid API `secret`. The `secret` is required and may be
            provided either in the `PLAID-SECRET` header or as part of a request body.
        access_token (str): The access token associated with the Item data is being
            requested for.
        account_id (str): The `account_id` of the account whose verification status
            is to be modified
        client_transaction_id (str): The unique ID that you would like to use to
            refer to this transaction. For your convenience mapping your internal
            data, you could use your internal ID/identifier for this transaction. The
            max length for this field is 36 characters.
        amount (float): The transaction amount, in USD (e.g. `102.05`)
        client_user_id (str): A unique ID that identifies the end user in your
            system. This ID is used to correlate requests by a user with multiple
            Items. The max length for this field is 36 characters.
        user (SignalUser): Details about the end user initiating the transaction
            (i.e., the account holder).
        device (SignalEvaluateDevice): Details about the end user's device
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access_token": "access_token",
        "account_id": "account_id",
        "client_transaction_id": "client_transaction_id",
        "amount": "amount",
        "client_id": "client_id",
        "secret": "secret",
        "client_user_id": "client_user_id",
        "user": "user",
        "device": "device",
    }

    _optionals = [
        "client_id",
        "secret",
        "client_user_id",
        "user",
        "device",
    ]

    def __init__(
        self,
        access_token=None,
        account_id=None,
        client_transaction_id=None,
        amount=None,
        client_id=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        client_user_id=APIHelper.SKIP,
        user=APIHelper.SKIP,
        device=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SignalEvaluateRequest instance."""
        # Initialize members of the class
        if client_id is not APIHelper.SKIP:
            self.client_id = client_id
        if secret is not APIHelper.SKIP:
            self.secret = secret
        self.access_token = access_token
        self.account_id = account_id
        self.client_transaction_id = client_transaction_id
        self.amount = amount
        if client_user_id is not APIHelper.SKIP:
            self.client_user_id = client_user_id
        if user is not APIHelper.SKIP:
            self.user = user
        if device is not APIHelper.SKIP:
            self.device = device

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        access_token =\
            dictionary.get("access_token")\
            if dictionary.get("access_token")\
                else None
        account_id =\
            dictionary.get("account_id")\
            if dictionary.get("account_id")\
                else None
        client_transaction_id =\
            dictionary.get("client_transaction_id")\
            if dictionary.get("client_transaction_id")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        client_user_id =\
            dictionary.get("client_user_id")\
            if dictionary.get("client_user_id")\
                else APIHelper.SKIP
        user =\
            SignalUser.from_dictionary(
                dictionary.get("user"))\
                if "user" in dictionary.keys()\
                else APIHelper.SKIP
        device =\
            SignalEvaluateDevice.from_dictionary(
                dictionary.get("device"))\
                if "device" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(access_token,
                   account_id,
                   client_transaction_id,
                   amount,
                   client_id,
                   secret,
                   client_user_id,
                   user,
                   device,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _access_token=self.access_token
        _account_id=self.account_id
        _client_transaction_id=self.client_transaction_id
        _amount=self.amount
        _client_user_id=(
            self.client_user_id
            if hasattr(self, "client_user_id")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _device=(
            self.device
            if hasattr(self, "device")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!r}, "
            f"secret={_secret!r}, "
            f"access_token={_access_token!r}, "
            f"account_id={_account_id!r}, "
            f"client_transaction_id={_client_transaction_id!r}, "
            f"amount={_amount!r}, "
            f"client_user_id={_client_user_id!r}, "
            f"user={_user!r}, "
            f"device={_device!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_id=(
            self.client_id
            if hasattr(self, "client_id")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _access_token=self.access_token
        _account_id=self.account_id
        _client_transaction_id=self.client_transaction_id
        _amount=self.amount
        _client_user_id=(
            self.client_user_id
            if hasattr(self, "client_user_id")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _device=(
            self.device
            if hasattr(self, "device")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_id={_client_id!s}, "
            f"secret={_secret!s}, "
            f"access_token={_access_token!s}, "
            f"account_id={_account_id!s}, "
            f"client_transaction_id={_client_transaction_id!s}, "
            f"amount={_amount!s}, "
            f"client_user_id={_client_user_id!s}, "
            f"user={_user!s}, "
            f"device={_device!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
