"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Subtype(object):
    """Implementation of the 'Subtype' enum.

    For descriptions of possible transaction types and subtypes, see the [Investment
    transaction types
    schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).

    Attributes:
        ENUM_ACCOUNT FEE: The enum member of type str.
        ASSIGNMENT: The enum member of type str.
        BUY: The enum member of type str.
        ENUM_BUY TO COVER: The enum member of type str.
        CONTRIBUTION: The enum member of type str.
        DEPOSIT: The enum member of type str.
        DISTRIBUTION: The enum member of type str.
        DIVIDEND: The enum member of type str.
        ENUM_DIVIDEND REINVESTMENT: The enum member of type str.
        EXERCISE: The enum member of type str.
        EXPIRE: The enum member of type str.
        ENUM_FUND FEE: The enum member of type str.
        INTEREST: The enum member of type str.
        ENUM_INTEREST RECEIVABLE: The enum member of type str.
        ENUM_INTEREST REINVESTMENT: The enum member of type str.
        ENUM_LEGAL FEE: The enum member of type str.
        ENUM_LOAN PAYMENT: The enum member of type str.
        ENUM_LONGTERM CAPITAL GAIN: The enum member of type str.
        ENUM_LONGTERM CAPITAL GAIN REINVESTMENT: The enum member of type str.
        ENUM_MANAGEMENT FEE: The enum member of type str.
        ENUM_MARGIN EXPENSE: The enum member of type str.
        MERGER: The enum member of type str.
        ENUM_MISCELLANEOUS FEE: The enum member of type str.
        ENUM_NONQUALIFIED DIVIDEND: The enum member of type str.
        ENUM_NONRESIDENT TAX: The enum member of type str.
        ENUM_PENDING CREDIT: The enum member of type str.
        ENUM_PENDING DEBIT: The enum member of type str.
        ENUM_QUALIFIED DIVIDEND: The enum member of type str.
        REBALANCE: The enum member of type str.
        ENUM_RETURN OF PRINCIPAL: The enum member of type str.
        SELL: The enum member of type str.
        ENUM_SELL SHORT: The enum member of type str.
        ENUM_SHORTTERM CAPITAL GAIN: The enum member of type str.
        ENUM_SHORTTERM CAPITAL GAIN REINVESTMENT: The enum member of type str.
        ENUM_SPIN OFF: The enum member of type str.
        SPLIT: The enum member of type str.
        ENUM_STOCK DISTRIBUTION: The enum member of type str.
        TAX: The enum member of type str.
        ENUM_TAX WITHHELD: The enum member of type str.
        TRANSFER: The enum member of type str.
        ENUM_TRANSFER FEE: The enum member of type str.
        ENUM_TRUST FEE: The enum member of type str.
        ENUM_UNQUALIFIED GAIN: The enum member of type str.
        WITHDRAWAL: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    ENUM_ACCOUNT_FEE = "account fee"

    ASSIGNMENT = "assignment"

    BUY = "buy"

    ENUM_BUY_TO_COVER = "buy to cover"

    CONTRIBUTION = "contribution"

    DEPOSIT = "deposit"

    DISTRIBUTION = "distribution"

    DIVIDEND = "dividend"

    ENUM_DIVIDEND_REINVESTMENT = "dividend reinvestment"

    EXERCISE = "exercise"

    EXPIRE = "expire"

    ENUM_FUND_FEE = "fund fee"

    INTEREST = "interest"

    ENUM_INTEREST_RECEIVABLE = "interest receivable"

    ENUM_INTEREST_REINVESTMENT = "interest reinvestment"

    ENUM_LEGAL_FEE = "legal fee"

    ENUM_LOAN_PAYMENT = "loan payment"

    ENUM_LONGTERM_CAPITAL_GAIN = "long-term capital gain"

    ENUM_LONGTERM_CAPITAL_GAIN_REINVESTMENT = "long-term capital gain reinvestment"

    ENUM_MANAGEMENT_FEE = "management fee"

    ENUM_MARGIN_EXPENSE = "margin expense"

    MERGER = "merger"

    ENUM_MISCELLANEOUS_FEE = "miscellaneous fee"

    ENUM_NONQUALIFIED_DIVIDEND = "non-qualified dividend"

    ENUM_NONRESIDENT_TAX = "non-resident tax"

    ENUM_PENDING_CREDIT = "pending credit"

    ENUM_PENDING_DEBIT = "pending debit"

    ENUM_QUALIFIED_DIVIDEND = "qualified dividend"

    REBALANCE = "rebalance"

    ENUM_RETURN_OF_PRINCIPAL = "return of principal"

    SELL = "sell"

    ENUM_SELL_SHORT = "sell short"

    ENUM_SHORTTERM_CAPITAL_GAIN = "short-term capital gain"

    ENUM_SHORTTERM_CAPITAL_GAIN_REINVESTMENT = "short-term capital gain reinvestment"

    ENUM_SPIN_OFF = "spin off"

    SPLIT = "split"

    ENUM_STOCK_DISTRIBUTION = "stock distribution"

    TAX = "tax"

    ENUM_TAX_WITHHELD = "tax withheld"

    TRANSFER = "transfer"

    ENUM_TRANSFER_FEE = "transfer fee"

    ENUM_TRUST_FEE = "trust fee"

    ENUM_UNQUALIFIED_GAIN = "unqualified gain"

    WITHDRAWAL = "withdrawal"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
