"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TransactionCode(object):
    """Implementation of the 'transaction_code' enum.

    An identifier classifying the transaction type.
    This field is only populated for European institutions. For institutions in the
    US and Canada, this field is set to `null`.
    `adjustment:` Bank adjustment
    `atm:` Cash deposit or withdrawal via an automated teller machine
    `bank charge:` Charge or fee levied by the institution
    `bill payment`: Payment of a bill
    `cash:` Cash deposit or withdrawal
    `cashback:` Cash withdrawal while making a debit card purchase
    `cheque:` Document ordering the payment of money to another person or organization
    `direct debit:` Automatic withdrawal of funds initiated by a third party at a
    regular interval
    `interest:` Interest earned or incurred
    `purchase:` Purchase made with a debit or credit card
    `standing order:` Payment instructed by the account holder to a third party at a
    regular interval
    `transfer:` Transfer of money between accounts

    Attributes:
        ADJUSTMENT: The enum member of type str.
        ATM: The enum member of type str.
        ENUM_BANK CHARGE: The enum member of type str.
        ENUM_BILL PAYMENT: The enum member of type str.
        CASH: The enum member of type str.
        CASHBACK: The enum member of type str.
        CHEQUE: The enum member of type str.
        ENUM_DIRECT DEBIT: The enum member of type str.
        INTEREST: The enum member of type str.
        PURCHASE: The enum member of type str.
        ENUM_STANDING ORDER: The enum member of type str.
        TRANSFER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    ADJUSTMENT = "adjustment"

    ATM = "atm"

    ENUM_BANK_CHARGE = "bank charge"

    ENUM_BILL_PAYMENT = "bill payment"

    CASH = "cash"

    CASHBACK = "cashback"

    CHEQUE = "cheque"

    ENUM_DIRECT_DEBIT = "direct debit"

    INTEREST = "interest"

    PURCHASE = "purchase"

    ENUM_STANDING_ORDER = "standing order"

    TRANSFER = "transfer"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
