"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class TransactionLocation(object):
    """Implementation of the 'TransactionLocation' model.

    A representation of where a transaction took place

    Attributes:
        address (str): The street address where the transaction occurred.
        city (str): The city where the transaction occurred.
        region (str): The region or state where the transaction occurred.
        postal_code (str): The postal code where the transaction occurred.
        country (str): The ISO 3166-1 alpha-2 country code where the transaction
            occurred.
        lat (float): The latitude where the transaction occurred.
        lon (float): The longitude where the transaction occurred.
        store_number (str): The merchant defined store number where the transaction
            occurred.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address": "address",
        "city": "city",
        "region": "region",
        "postal_code": "postal_code",
        "country": "country",
        "lat": "lat",
        "lon": "lon",
        "store_number": "store_number",
    }

    _nullables = [
        "address",
        "city",
        "region",
        "postal_code",
        "country",
        "lat",
        "lon",
        "store_number",
    ]

    def __init__(
        self,
        address=None,
        city=None,
        region=None,
        postal_code=None,
        country=None,
        lat=None,
        lon=None,
        store_number=None,
        additional_properties=None):
        """Initialize a TransactionLocation instance."""
        # Initialize members of the class
        self.address = address
        self.city = city
        self.region = region
        self.postal_code = postal_code
        self.country = country
        self.lat = lat
        self.lon = lon
        self.store_number = store_number

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address =\
            dictionary.get("address")\
            if dictionary.get("address")\
                else None
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else None
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else None
        postal_code =\
            dictionary.get("postal_code")\
            if dictionary.get("postal_code")\
                else None
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else None
        lat =\
            dictionary.get("lat")\
            if dictionary.get("lat")\
                else None
        lon =\
            dictionary.get("lon")\
            if dictionary.get("lon")\
                else None
        store_number =\
            dictionary.get("store_number")\
            if dictionary.get("store_number")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(address,
                   city,
                   region,
                   postal_code,
                   country,
                   lat,
                   lon,
                   store_number,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address=self.address
        _city=self.city
        _region=self.region
        _postal_code=self.postal_code
        _country=self.country
        _lat=self.lat
        _lon=self.lon
        _store_number=self.store_number
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address={_address!r}, "
            f"city={_city!r}, "
            f"region={_region!r}, "
            f"postal_code={_postal_code!r}, "
            f"country={_country!r}, "
            f"lat={_lat!r}, "
            f"lon={_lon!r}, "
            f"store_number={_store_number!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address=self.address
        _city=self.city
        _region=self.region
        _postal_code=self.postal_code
        _country=self.country
        _lat=self.lat
        _lon=self.lon
        _store_number=self.store_number
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address={_address!s}, "
            f"city={_city!s}, "
            f"region={_region!s}, "
            f"postal_code={_postal_code!s}, "
            f"country={_country!s}, "
            f"lat={_lat!s}, "
            f"lon={_lon!s}, "
            f"store_number={_store_number!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
