"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TransferEventType(object):
    """Implementation of the 'TransferEventType' enum.

    The type of event that this transfer represents.
    `pending`: A new transfer was created; it is in the pending state.
    `cancelled`: The transfer was cancelled by the client.
    `failed`: The transfer failed, no funds were moved.
    `posted`: The transfer has been successfully submitted to the payment network.
    `reversed`: A posted transfer was reversed.

    Attributes:
        PENDING: The enum member of type str.
        CANCELLED: The enum member of type str.
        FAILED: The enum member of type str.
        POSTED: The enum member of type str.
        REVERSED: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    PENDING = "pending"

    CANCELLED = "cancelled"

    FAILED = "failed"

    POSTED = "posted"

    REVERSED = "reversed"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
