"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class TransferAuthorizationDecisionRationale(object):
    """Implementation of the 'TransferAuthorizationDecisionRationale' model.

    The rationale for Plaid's decision regarding a proposed transfer. Will be null
    for `approved` decisions.

    Attributes:
        code (Code): A code representing the rationale for permitting or declining
            the proposed transfer. Possible values are:  `NSF` – Transaction likely
            to result in a return due to insufficient funds.  `RISK` - Transaction is
            high-risk.  `MANUALLY_VERIFIED_ITEM` – Item created via same-day micro
            deposits, limited information available. Plaid can only offer `permitted`
            as a transaction decision.  `LOGIN_REQUIRED` – Unable to collect the
            account information required for an authorization decision due to Item
            staleness. Can be rectified using Link update mode.  `ERROR` – Unable to
            collect the account information required for an authorization decision
            due to an error.
        description (str): A human-readable description of the code associated with a
            permitted transfer or transfer decline.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": "code",
        "description": "description",
    }

    def __init__(
        self,
        code=None,
        description=None,
        additional_properties=None):
        """Initialize a TransferAuthorizationDecisionRationale instance."""
        # Initialize members of the class
        self.code = code
        self.description = description

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(code,
                   description,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _code=self.code
        _description=self.description
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"code={_code!r}, "
            f"description={_description!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _code=self.code
        _description=self.description
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"code={_code!s}, "
            f"description={_description!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
