"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from plaid.api_helper import APIHelper
from plaid.models.payment_meta import PaymentMeta
from plaid.models.personal_finance_category_2 import (
    PersonalFinanceCategory2,
)
from plaid.models.transaction_location import (
    TransactionLocation,
)


class Transaction(object):
    """Implementation of the 'Transaction' model.

    A representation of a transaction

    Attributes:
        transaction_type (TransactionType): Please use the `payment_channel` field,
            `transaction_type` will be deprecated in the future.  `digital:`
            transactions that took place online.  `place:` transactions that were
            made at a physical location.  `special:` transactions that relate to
            banks, e.g. fees or deposits.  `unresolved:` transactions that do not fit
            into the other three types.
        pending_transaction_id (str): The ID of a posted transaction's associated
            pending transaction, where applicable.
        category_id (str): The ID of the category to which this transaction belongs.
            See [Categories](https://plaid.com/docs/#category-overview).  If the
            `transactions` object was returned by an Assets endpoint such as
            `/asset_report/get/` or `/asset_report/pdf/get`, this field will only
            appear in an Asset Report with Insights.
        category (List[str]): A hierarchical array of the categories to which this
            transaction belongs. See
            [Categories](https://plaid.com/docs/#category-overview).  If the
            `transactions` object was returned by an Assets endpoint such as
            `/asset_report/get/` or `/asset_report/pdf/get`, this field will only
            appear in an Asset Report with Insights.
        location (TransactionLocation): A representation of where a transaction took
            place
        payment_meta (PaymentMeta): Transaction information specific to inter-bank
            transfers. If the transaction was not an inter-bank transfer, all fields
            will be `null`.  If the `transactions` object was returned by a
            Transactions endpoint such as `/transactions/get`, the `payment_meta` key
            will always appear, but no data elements are guaranteed. If the
            `transactions` object was returned by an Assets endpoint such as
            `/asset_report/get/` or `/asset_report/pdf/get`, this field will only
            appear in an Asset Report with Insights.
        account_owner (str): The name of the account owner. This field is not
            typically populated and only relevant when dealing with sub-accounts.
        name (str): The merchant name or transaction description.  If the
            `transactions` object was returned by a Transactions endpoint such as
            `/transactions/get`, this field will always appear. If the `transactions`
            object was returned by an Assets endpoint such as `/asset_report/get/` or
            `/asset_report/pdf/get`, this field will only appear in an Asset Report
            with Insights.
        original_description (str): The string returned by the financial institution
            to describe the transaction. For transactions returned by
            `/transactions/get`, this field is in beta and will be omitted unless the
            client is both enrolled in the closed beta program and has set
            `options.include_original_description` to `true`.
        account_id (str): The ID of the account in which this transaction occurred.
        amount (float): The settled value of the transaction, denominated in the
            account's currency, as stated in `iso_currency_code` or
            `unofficial_currency_code`. Positive values when money moves out of the
            account; negative values when money moves in. For example, debit card
            purchases are positive; credit card payments, direct deposits, and
            refunds are negative.
        iso_currency_code (str): The ISO-4217 currency code of the transaction.
            Always `null` if `unofficial_currency_code` is non-null.
        unofficial_currency_code (str): The unofficial currency code associated with
            the transaction. Always `null` if `iso_currency_code` is non-`null`.
            Unofficial currency codes are used for currencies that do not have
            official ISO currency codes, such as cryptocurrencies and the currencies
            of certain countries.  See the [currency code
            schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a
            full listing of supported `iso_currency_code`s.
        date (date): For pending transactions, the date that the transaction
            occurred; for posted transactions, the date that the transaction posted.
            Both dates are returned in an [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) format ( `YYYY-MM-DD` ).
        pending (bool): When `true`, identifies the transaction as pending or
            unsettled. Pending transaction details (name, type, amount, category ID)
            may change before they are settled.
        transaction_id (str): The unique ID of the transaction. Like all Plaid
            identifiers, the `transaction_id` is case sensitive.
        payment_channel (PaymentChannel): The channel used to make a payment.
            `online:` transactions that took place online.  `in store:` transactions
            that were made at a physical location.  `other:` transactions that relate
            to banks, e.g. fees or deposits.  This field replaces the
            `transaction_type` field.
        merchant_name (str): The merchant name, as extracted by Plaid from the `name`
            field.
        authorized_date (date): The date that the transaction was authorized. Dates
            are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format
            ( `YYYY-MM-DD` ).
        authorized_datetime (datetime): Date and time when a transaction was
            authorized in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (
            `YYYY-MM-DDTHH:mm:ssZ` ).  This field is only populated for UK
            institutions. For institutions in other countries, will be `null`.
        datetime (datetime): Date and time when a transaction was posted in [ISO
            8601](https://wikipedia.org/wiki/ISO_8601) format (
            `YYYY-MM-DDTHH:mm:ssZ` ).  This field is only populated for UK
            institutions. For institutions in other countries, will be `null`.
        check_number (str): The check number of the transaction. This field is only
            populated for check transactions.
        transaction_code (TransactionCode): An identifier classifying the transaction
            type.  This field is only populated for European institutions. For
            institutions in the US and Canada, this field is set to `null`.
            `adjustment:` Bank adjustment  `atm:` Cash deposit or withdrawal via an
            automated teller machine  `bank charge:` Charge or fee levied by the
            institution  `bill payment`: Payment of a bill  `cash:` Cash deposit or
            withdrawal  `cashback:` Cash withdrawal while making a debit card
            purchase  `cheque:` Document ordering the payment of money to another
            person or organization  `direct debit:` Automatic withdrawal of funds
            initiated by a third party at a regular interval  `interest:` Interest
            earned or incurred  `purchase:` Purchase made with a debit or credit card
            `standing order:` Payment instructed by the account holder to a third
            party at a regular interval  `transfer:` Transfer of money between
            accounts
        personal_finance_category (PersonalFinanceCategory2): The model property of
            type PersonalFinanceCategory2.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pending_transaction_id": "pending_transaction_id",
        "category_id": "category_id",
        "category": "category",
        "location": "location",
        "payment_meta": "payment_meta",
        "account_owner": "account_owner",
        "name": "name",
        "account_id": "account_id",
        "amount": "amount",
        "iso_currency_code": "iso_currency_code",
        "unofficial_currency_code": "unofficial_currency_code",
        "date": "date",
        "pending": "pending",
        "transaction_id": "transaction_id",
        "payment_channel": "payment_channel",
        "merchant_name": "merchant_name",
        "authorized_date": "authorized_date",
        "authorized_datetime": "authorized_datetime",
        "datetime": "datetime",
        "check_number": "check_number",
        "transaction_code": "transaction_code",
        "transaction_type": "transaction_type",
        "original_description": "original_description",
        "personal_finance_category": "personal_finance_category",
    }

    _optionals = [
        "transaction_type",
        "original_description",
        "personal_finance_category",
    ]

    _nullables = [
        "pending_transaction_id",
        "category_id",
        "category",
        "account_owner",
        "original_description",
        "iso_currency_code",
        "unofficial_currency_code",
        "merchant_name",
        "authorized_date",
        "authorized_datetime",
        "datetime",
        "check_number",
    ]

    def __init__(
        self,
        pending_transaction_id=None,
        category_id=None,
        category=None,
        location=None,
        payment_meta=None,
        account_owner=None,
        name=None,
        account_id=None,
        amount=None,
        iso_currency_code=None,
        unofficial_currency_code=None,
        date=None,
        pending=None,
        transaction_id=None,
        payment_channel=None,
        merchant_name=None,
        authorized_date=None,
        authorized_datetime=None,
        datetime=None,
        check_number=None,
        transaction_code=None,
        transaction_type=APIHelper.SKIP,
        original_description=APIHelper.SKIP,
        personal_finance_category=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Transaction instance."""
        # Initialize members of the class
        if transaction_type is not APIHelper.SKIP:
            self.transaction_type = transaction_type
        self.pending_transaction_id = pending_transaction_id
        self.category_id = category_id
        self.category = category
        self.location = location
        self.payment_meta = payment_meta
        self.account_owner = account_owner
        self.name = name
        if original_description is not APIHelper.SKIP:
            self.original_description = original_description
        self.account_id = account_id
        self.amount = amount
        self.iso_currency_code = iso_currency_code
        self.unofficial_currency_code = unofficial_currency_code
        self.date = date
        self.pending = pending
        self.transaction_id = transaction_id
        self.payment_channel = payment_channel
        self.merchant_name = merchant_name
        self.authorized_date = authorized_date
        self.authorized_datetime =\
             APIHelper.apply_datetime_converter(
            authorized_datetime, APIHelper.RFC3339DateTime)\
             if authorized_datetime else None
        self.datetime =\
             APIHelper.apply_datetime_converter(
            datetime, APIHelper.RFC3339DateTime)\
             if datetime else None
        self.check_number = check_number
        self.transaction_code = transaction_code
        if personal_finance_category is not APIHelper.SKIP:
            self.personal_finance_category = personal_finance_category

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        pending_transaction_id =\
            dictionary.get("pending_transaction_id")\
            if dictionary.get("pending_transaction_id")\
                else None
        category_id =\
            dictionary.get("category_id")\
            if dictionary.get("category_id")\
                else None
        category =\
            dictionary.get("category")\
            if dictionary.get("category")\
                else None
        location =\
            TransactionLocation.from_dictionary(
                dictionary.get("location"))\
                if dictionary.get("location") else None
        payment_meta =\
            PaymentMeta.from_dictionary(
                dictionary.get("payment_meta"))\
                if dictionary.get("payment_meta") else None
        account_owner =\
            dictionary.get("account_owner")\
            if dictionary.get("account_owner")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        account_id =\
            dictionary.get("account_id")\
            if dictionary.get("account_id")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        iso_currency_code =\
            dictionary.get("iso_currency_code")\
            if dictionary.get("iso_currency_code")\
                else None
        unofficial_currency_code =\
            dictionary.get("unofficial_currency_code")\
            if dictionary.get("unofficial_currency_code")\
                else None
        date = dateutil.parser.parse(
            dictionary.get("date")).date()\
            if dictionary.get("date") else None
        pending =\
            dictionary.get("pending")\
            if "pending" in dictionary.keys()\
                else None
        transaction_id =\
            dictionary.get("transaction_id")\
            if dictionary.get("transaction_id")\
                else None
        payment_channel =\
            dictionary.get("payment_channel")\
            if dictionary.get("payment_channel")\
                else None
        merchant_name =\
            dictionary.get("merchant_name")\
            if dictionary.get("merchant_name")\
                else None
        authorized_date = dateutil.parser.parse(
            dictionary.get("authorized_date")).date()\
            if dictionary.get("authorized_date") else None
        authorized_datetime = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("authorized_datetime")).datetime\
            if dictionary.get("authorized_datetime") else None
        datetime = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("datetime")).datetime\
            if dictionary.get("datetime") else None
        check_number =\
            dictionary.get("check_number")\
            if dictionary.get("check_number")\
                else None
        transaction_code =\
            dictionary.get("transaction_code")\
            if dictionary.get("transaction_code")\
                else None
        transaction_type =\
            dictionary.get("transaction_type")\
            if dictionary.get("transaction_type")\
                else APIHelper.SKIP
        original_description =\
            dictionary.get("original_description")\
            if "original_description" in dictionary.keys()\
                else APIHelper.SKIP
        personal_finance_category =\
            PersonalFinanceCategory2.from_dictionary(
                dictionary.get("personal_finance_category"))\
                if "personal_finance_category" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(pending_transaction_id,
                   category_id,
                   category,
                   location,
                   payment_meta,
                   account_owner,
                   name,
                   account_id,
                   amount,
                   iso_currency_code,
                   unofficial_currency_code,
                   date,
                   pending,
                   transaction_id,
                   payment_channel,
                   merchant_name,
                   authorized_date,
                   authorized_datetime,
                   datetime,
                   check_number,
                   transaction_code,
                   transaction_type,
                   original_description,
                   personal_finance_category,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _pending_transaction_id=self.pending_transaction_id
        _category_id=self.category_id
        _category=self.category
        _location=self.location
        _payment_meta=self.payment_meta
        _account_owner=self.account_owner
        _name=self.name
        _original_description=(
            self.original_description
            if hasattr(self, "original_description")
            else None
        )
        _account_id=self.account_id
        _amount=self.amount
        _iso_currency_code=self.iso_currency_code
        _unofficial_currency_code=self.unofficial_currency_code
        _date=self.date
        _pending=self.pending
        _transaction_id=self.transaction_id
        _payment_channel=self.payment_channel
        _merchant_name=self.merchant_name
        _authorized_date=self.authorized_date
        _authorized_datetime=self.authorized_datetime
        _datetime=self.datetime
        _check_number=self.check_number
        _transaction_code=self.transaction_code
        _personal_finance_category=(
            self.personal_finance_category
            if hasattr(self, "personal_finance_category")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"transaction_type={_transaction_type!r}, "
            f"pending_transaction_id={_pending_transaction_id!r}, "
            f"category_id={_category_id!r}, "
            f"category={_category!r}, "
            f"location={_location!r}, "
            f"payment_meta={_payment_meta!r}, "
            f"account_owner={_account_owner!r}, "
            f"name={_name!r}, "
            f"original_description={_original_description!r}, "
            f"account_id={_account_id!r}, "
            f"amount={_amount!r}, "
            f"iso_currency_code={_iso_currency_code!r}, "
            f"unofficial_currency_code={_unofficial_currency_code!r}, "
            f"date={_date!r}, "
            f"pending={_pending!r}, "
            f"transaction_id={_transaction_id!r}, "
            f"payment_channel={_payment_channel!r}, "
            f"merchant_name={_merchant_name!r}, "
            f"authorized_date={_authorized_date!r}, "
            f"authorized_datetime={_authorized_datetime!r}, "
            f"datetime={_datetime!r}, "
            f"check_number={_check_number!r}, "
            f"transaction_code={_transaction_code!r}, "
            f"personal_finance_category={_personal_finance_category!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _pending_transaction_id=self.pending_transaction_id
        _category_id=self.category_id
        _category=self.category
        _location=self.location
        _payment_meta=self.payment_meta
        _account_owner=self.account_owner
        _name=self.name
        _original_description=(
            self.original_description
            if hasattr(self, "original_description")
            else None
        )
        _account_id=self.account_id
        _amount=self.amount
        _iso_currency_code=self.iso_currency_code
        _unofficial_currency_code=self.unofficial_currency_code
        _date=self.date
        _pending=self.pending
        _transaction_id=self.transaction_id
        _payment_channel=self.payment_channel
        _merchant_name=self.merchant_name
        _authorized_date=self.authorized_date
        _authorized_datetime=self.authorized_datetime
        _datetime=self.datetime
        _check_number=self.check_number
        _transaction_code=self.transaction_code
        _personal_finance_category=(
            self.personal_finance_category
            if hasattr(self, "personal_finance_category")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"transaction_type={_transaction_type!s}, "
            f"pending_transaction_id={_pending_transaction_id!s}, "
            f"category_id={_category_id!s}, "
            f"category={_category!s}, "
            f"location={_location!s}, "
            f"payment_meta={_payment_meta!s}, "
            f"account_owner={_account_owner!s}, "
            f"name={_name!s}, "
            f"original_description={_original_description!s}, "
            f"account_id={_account_id!s}, "
            f"amount={_amount!s}, "
            f"iso_currency_code={_iso_currency_code!s}, "
            f"unofficial_currency_code={_unofficial_currency_code!s}, "
            f"date={_date!s}, "
            f"pending={_pending!s}, "
            f"transaction_id={_transaction_id!s}, "
            f"payment_channel={_payment_channel!s}, "
            f"merchant_name={_merchant_name!s}, "
            f"authorized_date={_authorized_date!s}, "
            f"authorized_datetime={_authorized_datetime!s}, "
            f"datetime={_datetime!s}, "
            f"check_number={_check_number!s}, "
            f"transaction_code={_transaction_code!s}, "
            f"personal_finance_category={_personal_finance_category!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
