"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class VerificationRefreshStatus(object):
    """Implementation of the 'VerificationRefreshStatus' enum.

    The verification refresh status. One of the following:
    `"VERIFICATION_REFRESH_STATUS_USER_PRESENCE_REQUIRED"` User presence is required
    to refresh an income verification.

    Attributes:
        VERIFICATION_REFRESH_STATUS_USER_PRESENCE_REQUIRED: The enum member of type
            str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    VERIFICATION_REFRESH_STATUS_USER_PRESENCE_REQUIRED = "VERIFICATION_REFRESH_STATUS_USER_PRESENCE_REQUIRED" # noqa: E501

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
