"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class VerificationStatus3(object):
    """Implementation of the 'VerificationStatus3' enum.

    `VERIFICATION_STATUS_PROCESSING_COMPLETE`: The income verification status
    processing has completed.
    `VERIFICATION_STATUS_DOCUMENT_REJECTED`: The documentation uploaded by the end
    user was recognized as a supported file format, but not recognized as a valid
    paystub.
    `VERIFICATION_STATUS_PROCESSING_FAILED`: A failure occurred when attempting to
    process the verification documentation.

    Attributes:
        VERIFICATION_STATUS_PROCESSING_COMPLETE: The enum member of type str.
        VERIFICATION_STATUS_DOCUMENT_REJECTED: The enum member of type str.
        VERIFICATION_STATUS_PROCESSING_FAILED: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    VERIFICATION_STATUS_PROCESSING_COMPLETE = "VERIFICATION_STATUS_PROCESSING_COMPLETE"

    VERIFICATION_STATUS_DOCUMENT_REJECTED = "VERIFICATION_STATUS_DOCUMENT_REJECTED"

    VERIFICATION_STATUS_PROCESSING_FAILED = "VERIFICATION_STATUS_PROCESSING_FAILED"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
