"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class VerificationStatus(object):
    """Implementation of the 'VerificationStatus' enum.

    The verification status. One of the following:
    `"VERIFIED"`: The information was successfully verified.
    `"UNVERIFIED"`: The verification has not yet been performed.
    `"NEEDS_INFO"`: The verification was attempted but could not be completed due to
    missing information.
    "`UNABLE_TO_VERIFY`": The verification was performed and the information could
    not be verified.
    `"UNKNOWN"`: The verification status is unknown.

    Attributes:
        VERIFIED: The enum member of type str.
        UNVERIFIED: The enum member of type str.
        NEEDS_INFO: The enum member of type str.
        UNABLE_TO_VERIFY: The enum member of type str.
        UNKNOWN: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    VERIFIED = "VERIFIED"

    UNVERIFIED = "UNVERIFIED"

    NEEDS_INFO = "NEEDS_INFO"

    UNABLE_TO_VERIFY = "UNABLE_TO_VERIFY"

    UNKNOWN = "UNKNOWN"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
