"""plaid.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from plaid.api_helper import APIHelper


class W2StateAndLocalWages(object):
    """Implementation of the 'W2StateAndLocalWages' model.

    Attributes:
        state (str): State associated with the wage.
        employer_state_id_number (str): State identification number of the employer.
        state_wages_tips (str): Wages and tips from the specified state.
        state_income_tax (str): Income tax from the specified state.
        local_wages_tips (str): Wages and tips from the locality.
        local_income_tax (str): Income tax from the locality.
        locality_name (str): Name of the locality.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "state": "state",
        "employer_state_id_number": "employer_state_id_number",
        "state_wages_tips": "state_wages_tips",
        "state_income_tax": "state_income_tax",
        "local_wages_tips": "local_wages_tips",
        "local_income_tax": "local_income_tax",
        "locality_name": "locality_name",
    }

    _optionals = [
        "state",
        "employer_state_id_number",
        "state_wages_tips",
        "state_income_tax",
        "local_wages_tips",
        "local_income_tax",
        "locality_name",
    ]

    _nullables = [
        "state",
        "employer_state_id_number",
        "state_wages_tips",
        "state_income_tax",
        "local_wages_tips",
        "local_income_tax",
        "locality_name",
    ]

    def __init__(
        self,
        state=APIHelper.SKIP,
        employer_state_id_number=APIHelper.SKIP,
        state_wages_tips=APIHelper.SKIP,
        state_income_tax=APIHelper.SKIP,
        local_wages_tips=APIHelper.SKIP,
        local_income_tax=APIHelper.SKIP,
        locality_name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a W2StateAndLocalWages instance."""
        # Initialize members of the class
        if state is not APIHelper.SKIP:
            self.state = state
        if employer_state_id_number is not APIHelper.SKIP:
            self.employer_state_id_number = employer_state_id_number
        if state_wages_tips is not APIHelper.SKIP:
            self.state_wages_tips = state_wages_tips
        if state_income_tax is not APIHelper.SKIP:
            self.state_income_tax = state_income_tax
        if local_wages_tips is not APIHelper.SKIP:
            self.local_wages_tips = local_wages_tips
        if local_income_tax is not APIHelper.SKIP:
            self.local_income_tax = local_income_tax
        if locality_name is not APIHelper.SKIP:
            self.locality_name = locality_name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        state =\
            dictionary.get("state")\
            if "state" in dictionary.keys()\
                else APIHelper.SKIP
        employer_state_id_number =\
            dictionary.get("employer_state_id_number")\
            if "employer_state_id_number" in dictionary.keys()\
                else APIHelper.SKIP
        state_wages_tips =\
            dictionary.get("state_wages_tips")\
            if "state_wages_tips" in dictionary.keys()\
                else APIHelper.SKIP
        state_income_tax =\
            dictionary.get("state_income_tax")\
            if "state_income_tax" in dictionary.keys()\
                else APIHelper.SKIP
        local_wages_tips =\
            dictionary.get("local_wages_tips")\
            if "local_wages_tips" in dictionary.keys()\
                else APIHelper.SKIP
        local_income_tax =\
            dictionary.get("local_income_tax")\
            if "local_income_tax" in dictionary.keys()\
                else APIHelper.SKIP
        locality_name =\
            dictionary.get("locality_name")\
            if "locality_name" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(state,
                   employer_state_id_number,
                   state_wages_tips,
                   state_income_tax,
                   local_wages_tips,
                   local_income_tax,
                   locality_name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _employer_state_id_number=(
            self.employer_state_id_number
            if hasattr(self, "employer_state_id_number")
            else None
        )
        _state_wages_tips=(
            self.state_wages_tips
            if hasattr(self, "state_wages_tips")
            else None
        )
        _state_income_tax=(
            self.state_income_tax
            if hasattr(self, "state_income_tax")
            else None
        )
        _local_wages_tips=(
            self.local_wages_tips
            if hasattr(self, "local_wages_tips")
            else None
        )
        _local_income_tax=(
            self.local_income_tax
            if hasattr(self, "local_income_tax")
            else None
        )
        _locality_name=(
            self.locality_name
            if hasattr(self, "locality_name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"state={_state!r}, "
            f"employer_state_id_number={_employer_state_id_number!r}, "
            f"state_wages_tips={_state_wages_tips!r}, "
            f"state_income_tax={_state_income_tax!r}, "
            f"local_wages_tips={_local_wages_tips!r}, "
            f"local_income_tax={_local_income_tax!r}, "
            f"locality_name={_locality_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _employer_state_id_number=(
            self.employer_state_id_number
            if hasattr(self, "employer_state_id_number")
            else None
        )
        _state_wages_tips=(
            self.state_wages_tips
            if hasattr(self, "state_wages_tips")
            else None
        )
        _state_income_tax=(
            self.state_income_tax
            if hasattr(self, "state_income_tax")
            else None
        )
        _local_wages_tips=(
            self.local_wages_tips
            if hasattr(self, "local_wages_tips")
            else None
        )
        _local_income_tax=(
            self.local_income_tax
            if hasattr(self, "local_income_tax")
            else None
        )
        _locality_name=(
            self.locality_name
            if hasattr(self, "locality_name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"state={_state!s}, "
            f"employer_state_id_number={_employer_state_id_number!s}, "
            f"state_wages_tips={_state_wages_tips!s}, "
            f"state_income_tax={_state_income_tax!s}, "
            f"local_wages_tips={_local_wages_tips!s}, "
            f"local_income_tax={_local_income_tax!s}, "
            f"locality_name={_locality_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
