from __future__ import annotations

from pydantic import Field
from typing_extensions import TypedDict

from ..core import SdkBaseModel


class InflowModel(SdkBaseModel):
    """The ``inflow_model`` allows you to model a test account that receives regular income or make regular payments on
    a loan. Any transactions generated by the ``inflow_model`` will appear in addition to randomly generated test data
    or transactions specified by ``override_accounts``."""

    type_: str = Field(alias="type")
    """Inflow model. One of the following:

    ``none``: No income ``monthly-income``: Income occurs once per month ``monthly-balance-payment``: Pays off the
    balance on a liability account at the given statement day of month ``monthly-interest-only-payment``: Makes an
    interest-only payment on a liability account at the given statement day of month. Note that account types supported
    by Liabilities will accrue interest in the Sandbox. The types are account type ``credit`` with subtype ``credit`` or
    ``paypal``, and account type ``loan`` with subtype ``student`` or ``mortgage``."""

    income_amount: float
    """Amount of income per month. This value is required if ``type`` is ``monthly-income``."""

    payment_day_of_month: float
    """Number between 1 and 28, or ``last`` meaning the last day of the month. The day of the month on which the income
    transaction will appear. The name of the income transaction. This field is required if ``type`` is
    ``monthly-income``, ``monthly-balance-payment`` or ``monthly-interest-only-payment``."""

    transaction_name: str
    """The name of the income transaction. This field is required if ``type`` is ``monthly-income``,
    ``monthly-balance-payment`` or ``monthly-interest-only-payment``."""

    statement_day_of_month: str
    """Number between 1 and 28, or ``last`` meaning the last day of the month. The day of the month on which the balance
    is calculated for the next payment. The name of the income transaction. This field is required if ``type`` is
    ``monthly-balance-payment`` or ``monthly-interest-only-payment``."""


class InflowModelDict(TypedDict):
    type_: str
    income_amount: float
    payment_day_of_month: float
    transaction_name: str
    statement_day_of_month: str
