from __future__ import annotations

from pydantic import Field
from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel
from .enums.account_subtype import AccountSubtypeOrStr
from .enums.override_account_type import OverrideAccountTypeOrStr
from .holdings_override import HoldingsOverride, HoldingsOverrideDict
from .income_override import IncomeOverride, IncomeOverrideDict
from .inflow_model import InflowModel, InflowModelDict
from .investments_transactions_override import InvestmentsTransactionsOverride, InvestmentsTransactionsOverrideDict
from .liability_override import LiabilityOverride, LiabilityOverrideDict
from .meta import Meta, MetaDict
from .numbers import Numbers, NumbersDict
from .owner_override import OwnerOverride, OwnerOverrideDict
from .transaction_override import TransactionOverride, TransactionOverrideDict


class OverrideAccounts(SdkBaseModel):
    """Data to use to set values of test accounts. Some values cannot be specified in the schema and will instead will
    be calculated from other test data in order to achieve more consistent, realistic test data."""

    type_: OverrideAccountTypeOrStr = Field(alias="type")
    """``investment:`` Investment account

    ``credit:`` Credit card

    ``depository:`` Depository account

    ``loan:`` Loan account

    ``payroll:`` Payroll acccount

    ``other:`` Non-specified account type

    See the `Account type schema <https://plaid.com/docs/api/accounts#account-type-schema>`__ for a full listing of
    account types and corresponding subtypes."""

    subtype: AccountSubtypeOrStr
    """See the `Account type schema <https://plaid.com/docs/api/accounts/#account-type-schema>`__ for a full listing of
    account types and corresponding subtypes."""

    starting_balance: float
    """If provided, the account will start with this amount as the current balance."""

    force_available_balance: float
    """If provided, the account will always have this amount as its available balance, regardless of current balance or
    changes in transactions over time."""

    currency: str
    """ISO-4217 currency code. If provided, the account will be denominated in the given currency. Transactions will
    also be in this currency by default."""

    meta: Meta
    """Allows specifying the metadata of the test account"""

    numbers: Numbers
    """Account and bank identifier number data used to configure the test account. All values are optional."""

    transactions: list[TransactionOverride]
    """Specify the list of transactions on the account."""

    holdings: Optional[HoldingsOverride] = UNSET
    """Specify the holdings on the account."""

    investment_transactions: Optional[InvestmentsTransactionsOverride] = UNSET
    """Specify the list of investments transactions on the account."""

    identity: OwnerOverride
    """Data about the owner or owners of an account. Any fields not specified will be filled in with default Sandbox
    information."""

    liability: LiabilityOverride
    """Used to configure Sandbox test data for the Liabilities product"""

    inflow_model: InflowModel
    """The ``inflow_model`` allows you to model a test account that receives regular income or make regular payments on
    a loan. Any transactions generated by the ``inflow_model`` will appear in addition to randomly generated test data
    or transactions specified by ``override_accounts``."""

    income: Optional[IncomeOverride] = UNSET
    """Specify payroll data on the account."""


class OverrideAccountsDict(TypedDict):
    type_: OverrideAccountTypeOrStr
    subtype: AccountSubtypeOrStr
    starting_balance: float
    force_available_balance: float
    currency: str
    meta: MetaDict
    numbers: NumbersDict
    transactions: list[TransactionOverrideDict]
    holdings: NotRequired[HoldingsOverrideDict]
    investment_transactions: NotRequired[InvestmentsTransactionsOverrideDict]
    identity: OwnerOverrideDict
    liability: LiabilityOverrideDict
    inflow_model: InflowModelDict
    income: NotRequired[IncomeOverrideDict]
