from __future__ import annotations

from typing_extensions import TypedDict

from ..core import SdkBaseModel


class PersonalFinanceCategory(SdkBaseModel):
    """Information describing the intent of the transaction. Most relevant for personal finance use cases, but not
    limited to such use cases. The field is currently in beta.

    The complete category can be generated by concatenating primary and detailed categories.

    This feature is currently in beta – to request access, contact transactions-feedback@plaid.com."""

    primary: str
    """A high level category that communicates the broad category of the transaction."""

    detailed: str
    """Provides additional granularity to the primary categorization."""


class PersonalFinanceCategoryDict(TypedDict):
    primary: str
    detailed: str
